### ISSUE TITLE
手机自带的录屏功能开启后，录屏界面不能投到电脑

### ISSUE THREAD

**Issue by lyhdblny** [barry-ran/QtScrcpy#101]
首先，非常感谢作者贡献了这个好用的软件，非常赞。遇到的问题如题，手机自带一键录屏功能，打开录屏后，漂浮的录屏功能界面不能像手机桌面一样投屏到电脑。想请教下高手这是什么原因。之所以需要这个功能是因为我的手机漏液黑屏了，连在电脑上用。请指点。谢谢！

**Comment by barry-ran** [comment]
目前采集屏幕用的方案确实采集不到漂浮的录屏功能界面，本软件也可以录屏的
