### ISSUE TITLE
Mac 无法运行

### ISSUE THREAD

**Issue by limuyang2** [barry-ran/QtScrcpy#103]
打包的文件，有权限问题

**Comment by limuyang2** [comment]
1.2.1

**Comment by barry-ran** [comment]
低版本的没有权限问题吗？我想确认是QtScrcpy不同版本的问题？还是不同mac系统版本的问题？

**Comment by josephpei** [comment]
MacOS 10.15.3 ，提示“无法打开”

**Comment by GaryLee271** [comment]
我也是

**Comment by barry-ran** [comment]
下个版本我打成dmg包发布吧

**Comment by oxwo** [comment]
mac自带的解压包编码不同导致的  
我用的keka正常打开

**Comment by barry-ran** [comment]
[v1.3.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.3.0)已打包为dmg
