### ISSUE TITLE
荣耀 EMUI 10系统ifconfig取不了IP

### ISSUE THREAD

**Issue by firstuanl** [barry-ran/QtScrcpy#104]
EMUI 9可以，
EMUI 10用ifconfig取不了IP，提示无权限
用adb shell netcfg可以取得IP

**Comment by firstuanl** [comment]
取得IP后，有没命令启动投屏？

scrcpy用
`adb connect 192.168.2.233:5555
scrcpy --max-size 1080`

scrcpy刷新没qtscrcpy快

**Comment by barry-ran** [comment]
readme有介绍使用方法
