### ISSUE TITLE
Sndcpy ./adb no such file or directory

### ISSUE THREAD

**Issue by Danie10** [barry-ran/QtScrcpy#1046]
If you see this error:
```
"AudioOutput::" "/usr/bin/sndcpy.sh: line 40: ./adb: No such file or directory\n"
```
It is just a path error for adb as it is not found in that current directory where the sndcpy.sh script file resides. As adb is already in my path, I just changed line 6 to ```ADB=adb```

Hope this helps anyone else with sound issues.

**Comment by aliluys** [comment]
Nice bro.
