### ISSUE TITLE
VideoForm::mouseReleaseEvent函数判断逻辑不严谨

### ISSUE THREAD

**Issue by mo2phone** [barry-ran/QtScrcpy#11]
void VideoForm::mouseReleaseEvent(QMouseEvent *event)
{
    if (ui->videoWidget->geometry().contains(event->pos())) {
        if (!m_controller) {
            return;
        }
        event->setLocalPos(ui->videoWidget->mapFrom(this, event->localPos().toPoint()));
        m_controller->mouseEvent(event, ui->videoWidget->frameSize(), ui->videoWidget->size());
    }
}

如果这时候坐标越界了（即超过可是的video区域），界面可能处在拖动位置的中间。

**Comment by barry-ran** [comment]
[fixed](https://github.com/barry-ran/QtScrcpy/commit/4fd98deb676f6ec6d9e0a8abeba8ccfc7c1978ec)
