### ISSUE TITLE
和平精英移动偶尔会卡住一个方向移动控制不了

### ISSUE THREAD

**Issue by chuyatto** [barry-ran/QtScrcpy#114]

**Comment by XTTGO** [comment]
刷新脚本

**Comment by XTTGO** [comment]
自己手动的把 鼠标范围缩小  因为游戏左边是操控方向的，所以有时候鼠标会移动到那里

**Comment by sunqiyee** [comment]
同问，鼠标移动范围受限制，请问该如何修改 0.0 盼回复

**Comment by XTTGO** [comment]
> 同问，鼠标移动范围受限制，请问该如何修改 0.0 盼回复

等作者出能改的命令吧，现在的办法就是上车后 ~建切回 普通模式控制  下车点下车按钮，然后~按键切回吃鸡模式

**Comment by XTTGO** [comment]
这几天测试了下，卡方向应该是操作过于快，切换模式等操作导致，尽量避免操作太连贯，有节奏就好，然后脚本里鼠标速度我设置5，游戏里灵敏度低，提高鼠标的fps，可以减少卡顿鼠标和闪动视角的情况出现，然后比如下车上车视角不动，静止鼠标别动1-2s 左右 鼠标位置会归位

**Comment by barry-ran** [comment]
下车上车视角不动，可以连续按两次~键恢复
