### ISSUE TITLE
连接无线失败！获取不到设备IP

### ISSUE THREAD

**Issue by chenxu-Git** [barry-ran/QtScrcpy#116]
大佬，刷新设备可以看到
获取设备IP提示
start devices adbd...
adb run
AdbProcess::out:restarting in TCP mode port: 5555

get ip...
adb run

启动adba 设备直接断开 ，可以解决咩

**Comment by XueTeng2** [comment]
get ip...
adb run
AdbProcess::error:ifconfig: ioctl 8927: Permission denied
我的提示是这样

**Comment by chenxu-Git** [comment]
你是什么手机鸭



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XueTeng2"<notifications@github.com&gt;; 
发送时间: 2020年4月1日(星期三) 下午2:07
收件人: "barry-ran/QtScrcpy"<QtScrcpy@noreply.github.com&gt;; 
抄送: "饭团  &amp;#x1F1E8;&amp;#x1F1F3;"<122765923@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [barry-ran/QtScrcpy] 连接无线失败！获取不到设备IP (#116)





 
get ip...
 adb run
 AdbProcess::error:ifconfig: ioctl 8927: Permission denied
 我的提示是这样

**Comment by XueTeng2** [comment]
> 你是什么手机鸭
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "XueTeng2"<notifications@github.com&gt;; 发送时间: 2020年4月1日(星期三) 下午2:07 收件人: "barry-ran/QtScrcpy"<QtScrcpy@noreply.github.com&gt;; 抄送: "饭团 &amp;#x1F1E8;&amp;#x1F1F3;"<122765923@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [barry-ran/QtScrcpy] 连接无线失败！获取不到设备IP (#116) get ip... adb run AdbProcess::error:ifconfig: ioctl 8927: Permission denied 我的提示是这样 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

一加6T

**Comment by sc962** [comment]
> 
> 
> > 你是什么手机鸭
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "XueTeng2"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年4月1日(星期三) 下午2:07 收件人: "barry-ran/QtScrcpy"<[QtScrcpy@noreply.github.com](mailto:QtScrcpy@noreply.github.com)>; 抄送: "饭团 &#x1F1E8;&#x1F1F3;"<[122765923@qq.com](mailto:122765923@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [barry-ran/QtScrcpy] 连接无线失败！获取不到设备IP (#116) get ip... adb run AdbProcess::error:ifconfig: ioctl 8927: Permission denied 我的提示是这样 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 一加6T

请问问题解决没？同样的问题，用scrcpy就可以wifi，但是那个黑屏又无法控制。
这个啥都好，就是wifi无法连接

**Comment by barry-ran** [comment]
下个版本解决

**Comment by barry-ran** [comment]
[v1.3.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.3.1)已修复
