### ISSUE TITLE
VideoForm::mouseMoveEvent界面拖动的BUG；

### ISSUE THREAD

**Issue by mo2phone** [barry-ran/QtScrcpy#12]
void VideoForm::mouseMoveEvent(QMouseEvent *event)
{    
    if (ui->videoWidget->geometry().contains(event->pos())) {
        if (!m_controller) {
            return;
        }
        event->setLocalPos(ui->videoWidget->mapFrom(this, event->localPos().toPoint()));
        m_controller->mouseEvent(event, ui->videoWidget->frameSize(), ui->videoWidget->size());
    } else {
        if (event->buttons() & Qt::LeftButton) {
            move(event->globalPos() - m_dragPosition);
            event->accept();
        }
    }
}

   move(event->globalPos() - m_dragPosition);这会导致拖动的时候，界面被误操作拖动；

**Comment by barry-ran** [comment]
[fixed](https://github.com/barry-ran/QtScrcpy/commit/4fd98deb676f6ec6d9e0a8abeba8ccfc7c1978ec)
