### ISSUE TITLE
荣耀手机找不到设备

### ISSUE THREAD

**Issue by Kristen-Rose** [barry-ran/QtScrcpy#120]
荣耀无法找到设备

**Comment by barry-ran** [comment]
adb调试打开了吗？

**Comment by wenajiu** [comment]
我是华为手机。荣耀的我试过可以啊。

**Comment by Kristen-Rose** [comment]
是这样，大佬，我一直想找到一个投屏软件，了解到qtscrcpy
但是下载后无法连接，根据软件提示的list of devices attached，我上网查到可能是adb版本太低，于是问了问一位大佬，他说我的adb文件不在环境变量中，对于计算机不甚了解，我之后又看了csdn论坛，建立了一个advice. ini文件
到此为止，有线连接问题算是解决了
可是，当我重新尝试无线连接时问题又来了，软件提示我adb topic 5555
又是漫长的百度之旅，sdk文件下的adb，下载sdk后提示下载java，下载java后有不知道接下来该怎么做
文笔不好，但是折腾的很辛苦，希望大佬能指点一二



---原始邮件---
发件人: "Barry"<notifications@github.com&gt;
发送时间: 2020年4月12日(周日) 中午1:35
收件人: "barry-ran/QtScrcpy"<QtScrcpy@noreply.github.com&gt;;
抄送: "Kristen-Rose"<2920544291@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [barry-ran/QtScrcpy] 荣耀手机找不到设备 (#120)




 
adb调试打开了吗？

**Comment by barry-ran** [comment]
加qq群直接联系我给你远程

**Comment by Kristen-Rose** [comment]
谢谢大佬，自己又查了查百度，问题算是大部分解决了
麻烦您了



---原始邮件---
发件人: "Barry"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 下午2:16
收件人: "barry-ran/QtScrcpy"<QtScrcpy@noreply.github.com&gt;;
抄送: "Kristen-Rose"<2920544291@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [barry-ran/QtScrcpy] 荣耀手机找不到设备 (#120)




 
加qq群直接联系我给你远程

**Comment by z740332251** [comment]
请问是如何解决的？
我目前可以通过该项目自带的adb命令控制我的手机，但是该项目的界面中仍然不断输出：
```shell
update devices...
adb run
update devices...
adb run
...
```
像这样的输出如此反复。
我的手机信息：
device product:OXF-AN10 model:OXF_AN10 device:HWOXF transport_id:11
HarmonyOS: 3.0.0
