### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Michaelwang21** [barry-ran/QtScrcpy#121]
这个软件，在我的电脑上会闪退。。

我的系统版本：Macos 10.15.3
软件版本：1.3.0
手机：荣耀V9（Emui9.1.0）

问题出现的情况：触控板两个指头一划，软件就闪退了。（双指往左右一划，马上闪退。双指上下划，大概率闪退。）

**Comment by barry-ran** [comment]
[v1.3.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.3.1)已修复
