### ISSUE TITLE
标点符号无法在手机上用电脑打出

### ISSUE THREAD

**Issue by zhl111** [barry-ran/QtScrcpy#124]
这个能解决就好了。

**Comment by wenajiu** [comment]
切换输入法试试？？

**Comment by zhl111** [comment]
换了三种输入法都不行，搜狗，三星，gboard。

**Comment by zhl111** [comment]
用scrcpy可以输入标点符号，回过来再试这款还是不行

**Comment by Marshallmaxiao** [comment]
> 用scrcpy可以输入标点符号，回过来再试这款还是不行

我用scrcpy也不可以输入标点符号（搜狗、讯飞输入法都失败了），中英文模式都不行，请问你在scrcpy是怎么输入的？

**Comment by barry-ran** [comment]
Duplicate of #154
