### ISSUE TITLE
huawei手机，手机息屏后，电脑端唤醒手机后，手势解锁界面无法显示！是黑屏状态！只能盲操！

### ISSUE THREAD

**Issue by wenajiu** [barry-ran/QtScrcpy#126]
_**huawei手机，手机息屏后，电脑端唤醒手机后，手势解锁界面无法显示！是黑屏状态！只能盲操！**_请作者尽快修复这个bug !  thanks!
![1](https://user-images.githubusercontent.com/63531929/79061795-29825e80-7cc6-11ea-9fd4-45f49ab47ad9.png)

**Comment by barry-ran** [comment]
密码输入界面安全性较高，采集不到这个界面的视频，scrcpy效果一样

**Comment by MYZ6** [comment]
结合各位大神的思路，总算找到一个能用的办法，用adb模拟点击屏幕，事先计算好数字的位置，写先bat脚本，还算稳
![test](https://user-images.githubusercontent.com/3929396/205300823-dd47a972-f3d6-4e68-9588-d4ac2e630287.png)

**Comment by Hyphen-H** [comment]
可行，小米14 Ultra 分辨率1440*3200 一键解锁
笨方法，先用iPad给手机密码页面拍照，截成长方形，然后电脑上用Snipaste 贴图，再截屏(记录此分辨率，如`500*1080`，后面要等比放大到手机原始分辨率)
记录xy坐标
Snipaste原始的xy数据可以拿来用，显示多少就记录多少，如`123` `456`就是`x` `y`
再让ChatGPT按比例映射x和y的坐标，最终要映射/放大到手机原始分辨率
```
adb shell input keyevent KEYCODE_POWER #模拟按一下电源键
timeout /t 1 /nobreak
adb shell input swipe 576 1600 576 800 #模拟在屏幕中右侧五分之二处上滑
timeout /t 1 /nobreak
adb shell input tap mapped-x-coordinate mapped-y-coordinate
adb shell input tap mapped-x-coordinate mapped-y-coordinate
adb shell input tap mapped-x-coordinate mapped-y-coordinate
adb shell input tap mapped-x-coordinate mapped-y-coordinate
```
