### ISSUE TITLE
【问题】关于软件还有提速的空间吗？（希望作者抽空回复，谢谢）

### ISSUE THREAD

**Issue by XTTGO** [barry-ran/QtScrcpy#127]
比如刷新率的提高？或者更稳定
因为现在有tyc口，很多是3.0了 传输速度都可以上去了。现在软件可以全速传输嘛，我在软件里看到的一些速度大约在 4M/s  （每次启动都会看到）
还有如果用分线器 分出 hdmi 的模式呢？然后usb 还是可以控制手机是吧

**Comment by barry-ran** [comment]
没有提速空间了
