### ISSUE TITLE
魅族手机连接后显示的黑屏但能操作

### ISSUE THREAD

**Issue by Pytaya** [barry-ran/QtScrcpy#129]
start server...
getScreenRect is empty

AdbProcess::out:E:/Desktop/QtScrcpy-win-x64-v1.3.1/scrcpy-server: 1 file pushed. 5.4 MB/s (26142 bytes in 0.005s)

server start finish in 1.19s

getScreenRect is empty

QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
ERROR: 0:8: '' : No precision specified for (float)
ERROR: 0:9: '' : No precision specified for (float)
ERROR: 0:11: '' : No precision specified for (float)
ERROR: 0:12: '' : No precision specified for (float)
ERROR: 0:13: '' : No precision specified for (float)

*** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#line 1

    varying vec2 textureOut;        // ???????????????
    uniform sampler2D textureY;     // uniform ???????????????????
    uniform sampler2D textureU;     // sampler2D?2D???
    uniform sampler2D textureV;     // ??yuv??????
    void main(void)
    {
        vec3 yuv;
        vec3 rgb;
        // SDL2-2.0.10\src\render\opengl\SDL_shaders_gl.c BT709_SHADER_CONSTANTS
        const vec3 Rcoeff = vec3(1.1644,  0.000,  1.7927);
        const vec3 Gcoeff = vec3(1.1644, -0.2132, -0.5329);
        const vec3 Bcoeff = vec3(1.1644,  2.1124,  0.000);
        // ???????textureY???textureOut???
        yuv.x = texture2D(textureY, textureOut).r;
        yuv.y = texture2D(textureU, textureOut).r - 0.5;
        yuv.z = texture2D(textureV, textureOut).r - 0.5;
        // ?????rgb
        rgb.r = dot(yuv, Rcoeff);
        rgb.g = dot(yuv, Gcoeff);
        rgb.b = dot(yuv, Bcoeff);
        // ?????
        gl_FragColor = vec4(rgb, 1.0);
    }

***

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

**Comment by barry-ran** [comment]
https://github.com/barry-ran/QtScrcpy/blob/master/docs/FAQ.md
