### ISSUE TITLE
可否开放用户自定义比特率

### ISSUE THREAD

**Issue by YuCarl77** [barry-ran/QtScrcpy#136]
个人认为如果用户可控比特率可以控制WIFI下的传输画质和速度，因为太低的话又模糊，太高可能网络上传带不动导致延时等

**Comment by barry-ran** [comment]
目前2M-10M的比特率不够用吗？

**Comment by YuCarl77** [comment]
主要还是2 4 6 8 10M的比特率，如果说是以OBS开直播为例，每多1M对上传带宽量就不是同一个需求
