### ISSUE TITLE
未来是否考虑增加宏按键实现逐次点击

### ISSUE THREAD

**Issue by YuCarl77** [barry-ran/QtScrcpy#137]
比如方便吃鸡的打药或者手雷的切换、多个按键支持F键等

**Comment by fairytale110** [comment]
你是卖软件的？

**Comment by dockfries** [comment]
想多了，都是业内的没必要

**Comment by YuCarl77** [comment]
不过说实话给我整傻了，本身只是怀着提意见的态度被怀疑是拿你开源去卖钱，太委屈了。

**Comment by fairytale110** [comment]
> 不过说实话给我整傻了，本身只是怀着提意见的态度被怀疑是拿你开源去卖钱，太委屈了。

哥，那个，，，我不是作者，，，，我只是路过的，，，，
