### ISSUE TITLE
QTScrcpy can not work?

### ISSUE THREAD

**Issue by hongjojjay** [barry-ran/QtScrcpy#140]
Android 9.0 platform, running QTScrcpy 1.3.1 version, can not work, error infor as below:

This software is completely open source and free. Strictly used for illegal purposes, or at your own risk. You can download it at the following address:

"QtScrcpy 1.3.1 <https://github.com/barry-ran/QtScrcpy>"

adb devices
adb run
AdbProcess::out:List of devices attached
1234567	device

start server...
getScreenRect is empty

AdbProcess::out:D:/zst/QtScrcpy-win-x64-v1.3.1/scrcpy-server: 1 file pushed. 4.7 MB/s (26142 bytes in 0.005s)

server start finish in 1.073s

getScreenRect is empty

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored
[server] ERROR: Exception on thread Thread[main,5,main]
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024

AdbProcess::error:android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1960)
	at android.media.MediaCodec.configure(MediaCodec.java:1889)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

**Comment by barry-ran** [comment]
What device is 1234567? Try to reduce the resolution

**Comment by hongjojjay** [comment]
> What device is 1234567? Try to reduce the resolution

Hi, morning, the "1234567" is our inner device.

**Comment by barry-ran** [comment]
Try to reduce the resolution?

**Comment by hongjojjay** [comment]
> Try to reduce the resolution?

first solution: reduce the resolution
second solution: firstly adb root and adb remount, then no need to reduce the resolution, it is ok.

**Comment by devpatel777** [comment]
when i try to access my system via rdp and try to access qtscrcpy then i can open qyscrpy but i cant see device's display.
is it because openGL?
