### ISSUE TITLE
色彩问题

### ISSUE THREAD

**Issue by hhyacg** [barry-ran/QtScrcpy#147]
感觉亮度高了，不管是模拟器还是手机都是这样（难道说这样设计是为了方便观察？)
![image](https://user-images.githubusercontent.com/40420771/80190483-fa190d80-8646-11ea-8bae-4b780ac73980.png)

**Comment by barry-ran** [comment]
[v1.3.2](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.3.2)已修复

**Comment by barry-ran** [comment]
#119

**Comment by barry-ran** [comment]
Duplicate of #119

**Comment by barry-ran** [comment]
#119
