### ISSUE TITLE
adb tcpip 关闭

### ISSUE THREAD

**Issue by mcxinyu** [barry-ran/QtScrcpy#153]
这个问题可能跟这个项目没有直接关系，但是我在其他地方找不到答案。

我使用adb tcpip 5555 设置了之后，就算关闭、重启adb，只要插上手机就会看到ip的连接，这样影响了我使用adb服务，每次都要指定ip，请问如何关闭呢？

**Comment by barry-ran** [comment]
重启手机可以关闭adbd
