### ISSUE TITLE
【求助】红米2刷的魔趣rom安卓9.0，QtScrcpy显示黑屏但是鼠标操作触摸管用。

### ISSUE THREAD

**Issue by qq1056123185** [barry-ran/QtScrcpy#157]
【求助】红米2刷的魔趣rom安卓9.0，QtScrcpy显示黑屏但是鼠标操作触摸管用。

**Comment by qq1056123185** [comment]
红米2刷的魔趣rom，安卓版本是9.0，QtScrcpy显示的是黑屏，但是用鼠标在黑屏上面滑动，手机上面也可以动，也就是说通过QtScrcpy操作触摸是管用的，各位大佬，这种情况怎么处理，是BUG还是我个人手机的问题，希望帮忙解答一下，在此感谢！

**Comment by colinhd8** [comment]
find 7 刷的官方的coloros 2.0 (官卓5.0)  ，一模一样的问题，黑屏，但操作都是有效的。

**Comment by barry-ran** [comment]
#129

**Comment by barry-ran** [comment]
Duplicate of #129
