### ISSUE TITLE
win10,和平精英脚本无法应用

### ISSUE THREAD

**Issue by ataft7** [barry-ran/QtScrcpy#158]
win10,和平精英脚本无法应用，显示Script updated. 按键没有反应。

**Comment by fairytale110** [comment]
锁定了才行，，看看文档有说明

**Comment by barry-ran** [comment]
仔细阅读使用说明

**Comment by ataft7** [comment]
已解决，现在在调按键。哈哈

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Barry <notifications@github.com>
发送时间: Thursday, May 7, 2020 11:58:09 AM
收件人: barry-ran/QtScrcpy <QtScrcpy@noreply.github.com>
抄送: ataft7 <ataft7@outlook.com>; Author <author@noreply.github.com>
主题: Re: [barry-ran/QtScrcpy] win10,和平精英脚本无法应用 (#158)


仔细阅读使用说明

―
