### ISSUE TITLE
主程序名称为乱码

### ISSUE THREAD

**Issue by shikkoku** [barry-ran/QtScrcpy#166]
![批注 2020-05-12 203645](https://user-images.githubusercontent.com/4697177/81692166-8b361400-9490-11ea-9b2b-a38a70966dc6.jpg)

下载的文件包为https://github.com/barry-ran/QtScrcpy/releases/tag/v1.3.3
的QtScrcpy-win-x64-v1.3.3.zip

任务管理器上显示的进程名称亦一样为乱码显示。

**Comment by barry-ran** [comment]
感谢反馈，下个版本修复
