### ISSUE TITLE
只有native支持18：9，其他不支持

### ISSUE THREAD

**Issue by KingBillSame** [barry-ran/QtScrcpy#17]
而且native横屏也不支持18：9

**Comment by lengthmin** [comment]
是的，横屏就不舒服了

**Comment by yewang422** [comment]
更改Device.jar 112 行
switch (maxSize) {
            case 480: // 480p:640x480
                newWidth = 480;
                newHeight = 272;
                validSize = true;
                break;
            case 720: // 720p:1280x720
                newWidth = 720;
                newHeight = 408;
                validSize = true;
                break;
            case 1080: // 1080p:1920x1080
                newWidth = 1920;
                newHeight = 1080;
                validSize = true;
                break;
        }

**Comment by barry-ran** [comment]
目前只支持两种显示方式：
1. native 按照手机实际像素比例
2. 480p/720p等标准像素比例

**Comment by lengthmin** [comment]
native 状态下横屏有 bug

**Comment by barry-ran** [comment]
> native 状态下横屏比例有 bug

什么bug？可以详细说明吗？例如截图看看？
