### ISSUE TITLE
希望能在加入脚本的快速重启，以解决卡方向问题。

### ISSUE THREAD

**Issue by 779822364** [barry-ran/QtScrcpy#172]
卡方向问题一直存在，比如开车加速时，AW按住的同时鼠标移动视角卡住方向轮盘的概率非常大。以及钢枪的时候手速快转动视角又按着方向轮盘左右走位，还按蹲和躺来躲避子弹也非常容易卡住方向轮盘。这些问题，我希望能加入一个快捷快速重启脚本来解决。目前只能通过重启服务才能正常。

**Comment by yxtj** [comment]
这个问题我暂时也没有办法，我们还在研究。
一个已知的原因是开了陀螺仪导致的，你可以先排除一下。

另外按你的描述，我觉得你是不需要重启服务的，直接点击“应用脚本”，程序会自动停用当前脚本然后重新加载一遍。

**Comment by barry-ran** [comment]
#185
