### ISSUE TITLE
如何保持可操作状态

### ISSUE THREAD

**Issue by StrollStars** [barry-ran/QtScrcpy#174]
在设置一定时间休眠的情况下，如果超过这个时间没有操作，手机进入休眠，虽然连接还在，但是要继续操作需要解锁。请问有办法可以一直保持亮屏可操作的状态吗？
PS：最好是电脑一直可操作手机，而手机一直熄屏的状态。

**Comment by barry-ran** [comment]
手机设置-显示-调整休眠时间
