### ISSUE TITLE
Can't we Install after building ?

### ISSUE THREAD

**Issue by aiamuzz** [barry-ran/QtScrcpy#18]
```
PC client
Set up the Qt development environment on the target platform (Qt >= 5.9.7, vs >= 2015 (not support mingw))
Clone the project
Open the project root directory all.pro with QtCreator
Compile and run
```
@barry-ran ... i was wondering how do i install it permanently on my linux system !
Do i have to always run it through QtCreator ?
Would be nice if i could install it as an app and launch it directly !!!

**Comment by barry-ran** [comment]
Permanent installation on Linux is entirely feasible, but now you need to do it yourself, such as Google Search for "qt Linux release"
In the future, I may add a description of Linux release
