### ISSUE TITLE
Request: double click without button lift or make W similar to hold click

### ISSUE THREAD

**Issue by Al3busse** [barry-ran/QtScrcpy#180]
Hi, i would love if you can add that kind of type to the button keymap config, i was trying ark mobile and in order to sprint, you have to double press the left side of the screen (there is no sprint button to map), clicking and hold works with autosprint but holding W doesnt. Any tip on how to keymap it to make it work?

**Comment by yxtj** [comment]
We have the "KMT_CLICK_TWICE" type. You can map a key to that type of action.

**Comment by Al3busse** [comment]
I tried, but it didnt work, seems like the clicks cant be in the same spot, even with the mouse double clicks wont work if you dont click with a minimum separation one from another.

Maybe i can code the double click  "KMT_CLICK_TWICE" to click 1px away the second time if you could point me to the src code of it.

**Comment by yxtj** [comment]
> I tried, but it didnt work, seems like the clicks cant be in the same spot, even with the mouse double clicks wont work if you dont click with a minimum separation one from another.
> 
> Maybe i can code the double click "KMT_CLICK_TWICE" to click 1px away the second time if you could point me to the src code of it.

Maybe you can try KMT_DRAG for your game. We have an example in the script for "Identity V".
To perfectly solve your problem, I think we may need an action-composition function for the key mapping logic. But our recent plan does not cover it.

For now, if drag does not work, you can try to make two click-mappings.

**Comment by Al3busse** [comment]
The drag is actually a jump motion for this game, well the space bar works, even it has no on screen button or mapped (probably has to do with controller mapped for bluetooth controllers)


Thansk for the responses :)
