### ISSUE TITLE
ADB error

### ISSUE THREAD

**Issue by kkgiao** [barry-ran/QtScrcpy#181]
get ip...
adb run
AdbProcess::error:ifconfig: ioctl 8927: Permission denied

adb run
AdbProcess::out:1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
1: lo    inet6 ::1/128 scope host \       valid_lft forever preferred_lft forever
2: dummy0    inet6 fe80::34b7:9dff:fe6e:acf3/64 scope link \       valid_lft forever preferred_lft forever
14: rmnet_ims00    inet6 2605:b100:817:cecf:0:8:31e4:c301/64 scope global \       valid_lft forever preferred_lft forever
14: rmnet_ims00    inet6 fe80::5a02:3ff:fe04:50d/64 scope link \       valid_lft forever preferred_lft forever
34: wlan0    inet 10.0.0.195/24 brd 10.0.0.255 scope global wlan0\       valid_lft forever preferred_lft forever
34: wlan0    inet6 2604:3d08:517f:1100:e060:5e41:1409:5e53/64 scope global temporary dynamic \       valid_lft 287sec preferred_lft 287sec
34: wlan0    inet6 2604:3d08:517f:1100:e634:93ff:feb2:cb4d/64 scope global dynamic mngtmpaddr \       valid_lft 287sec preferred_lft 287sec
34: wlan0    inet6 fe80::e634:93ff:feb2:cb4d/64 scope link \       valid_lft forever preferred_lft forever
35: p2p0    inet6 fe80::e434:93ff:feb2:cb4d/64 scope link \       valid_lft forever preferred_lft forever

**Comment by barry-ran** [comment]
Can't connect ？

**Comment by kkgiao** [comment]
cant wireless connect
华为mate20 pro

Barry <notifications@github.com> 于 2020年5月24日周日 上午4:40写道：

**Comment by barry-ran** [comment]
Can't get ip address？

**Comment by kkgiao** [comment]
i think it can, it got the same ip as the phone. Would it be my phone's
setting? But i had the usb debugging on. It worked when it was wired

Barry <notifications@github.com> 于 2020年5月24日周日 上午4:46写道：

**Comment by barry-ran** [comment]
show me screenshot and more log

**Comment by kkgiao** [comment]
thanks, i'll do it when i wake up😂

Barry <notifications@github.com> 于 2020年5月24日周日 上午4:50写道：
