### ISSUE TITLE
请求增加mouseMoveMap类型映射的静止自动重置的时间设置

### ISSUE THREAD

**Issue by 748062672** [barry-ran/QtScrcpy#190]
在刺激战场中会经常出现鼠标实际在拖动触摸映射，但游戏不响应的情况，造成鼠标无法控制游戏视角，必须要鼠标静止不动一段时间后，等mouseMoveMap映射自动重置中心点，下次再重新触摸，游戏才会响应，现在鼠标静止不动的自动重置（大概两秒左右）有点过久....希望能有配置提供修改

**Comment by 748062672** [comment]
方向遥感也有概率出现映射后游戏不响应的情况 从手机显示的指针位置上看 是有触摸移动的 但是游戏就是会无视

**Comment by 748062672** [comment]
[5a80b050174e41b7f18acefb71cf54aa.zip](https://github.com/barry-ran/QtScrcpy/files/4707166/5a80b050174e41b7f18acefb71cf54aa.zip)
这是演示录屏

**Comment by barry-ran** [comment]
#185

**Comment by barry-ran** [comment]
Duplicate of 185#

**Comment by barry-ran** [comment]
Duplicate of #185
