### ISSUE TITLE
shader program is not linked while executing "QTSCRCPY" on window 7 64 bit

### ISSUE THREAD

**Issue by Subh222** [barry-ran/QtScrcpy#193]
@barry-ran Please help brother !!!
@yxtj @jabin-ma @shenzhigang @jaredtao 
This software is completely open source and free. Strictly used for illegal purposes, or at your own risk. You can download it at the following address:

"QtScrcpy 1.3.5 <https://github.com/barry-ran/QtScrcpy>"

update devices...
adb run
AdbProcess::out:List of devices attached
CGG3Y18B22008417	device

start server...
getScreenRect is empty

AdbProcess::out:C:/QtScrcpy-win-x64-v1.3.5/scrcpy-server: 1 file pushed. 0.3 MB/s (26142 bytes in 0.079s)

server start finish in 1.393s

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
ERROR: 0:8: '' : No precision specified for (float)
ERROR: 0:9: '' : No precision specified for (float)
ERROR: 0:13: '' : No precision specified for (float)
ERROR: 0:14: '' : No precision specified for (float)
ERROR: 0:15: '' : No precision specified for (float)

*** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#line 1

    varying vec2 textureOut;        // ???????????????
    uniform sampler2D textureY;     // uniform ???????????????????
    uniform sampler2D textureU;     // sampler2D?2D???
    uniform sampler2D textureV;     // ??yuv??????
    void main(void)
    {
        vec3 yuv;
        vec3 rgb;

        // SDL2 BT709_SHADER_CONSTANTS
        // https://github.com/spurious/SDL-mirror/blob/4ddd4c445aa059bb127e101b74a8c5b59257fbe2/src/render/opengl/SDL_shaders_gl.c#L102
        const vec3 Rcoeff = vec3(1.1644,  0.000,  1.7927);
        const vec3 Gcoeff = vec3(1.1644, -0.2132, -0.5329);
        const vec3 Bcoeff = vec3(1.1644,  2.1124,  0.000);

        // ???????textureY???textureOut???
        yuv.x = texture2D(textureY, textureOut).r;
        yuv.y = texture2D(textureU, textureOut).r - 0.5;
        yuv.z = texture2D(textureV, textureOut).r - 0.5;

        // ?????rgb
        // ??????
        yuv.x = yuv.x - 0.0625;
        rgb.r = dot(yuv, Rcoeff);
        rgb.g = dot(yuv, Gcoeff);
        rgb.b = dot(yuv, Bcoeff);
        // ?????
        gl_FragColor = vec4(rgb, 1.0);
    }

***

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

update devices...
adb run
AdbProcess::out:List of devices attached
CGG3Y18B22008417	device

start server...
getScreenRect is empty

AdbProcess::out:C:/QtScrcpy-win-x64-v1.3.5/scrcpy-server: 1 file pushed. 4.7 MB/s (26142 bytes in 0.005s)

server start finish in 0.811s

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

AdbProcess::out:

QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
ERROR: 0:8: '' : No precision specified for (float)
ERROR: 0:9: '' : No precision specified for (float)
ERROR: 0:13: '' : No precision specified for (float)
ERROR: 0:14: '' : No precision specified for (float)
ERROR: 0:15: '' : No precision specified for (float)

*** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#line 1

    varying vec2 textureOut;        // ???????????????
    uniform sampler2D textureY;     // uniform ???????????????????
    uniform sampler2D textureU;     // sampler2D?2D???
    uniform sampler2D textureV;     // ??yuv??????
    void main(void)
    {
        vec3 yuv;
        vec3 rgb;

        // SDL2 BT709_SHADER_CONSTANTS
        // https://github.com/spurious/SDL-mirror/blob/4ddd4c445aa059bb127e101b74a8c5b59257fbe2/src/render/opengl/SDL_shaders_gl.c#L102
        const vec3 Rcoeff = vec3(1.1644,  0.000,  1.7927);
        const vec3 Gcoeff = vec3(1.1644, -0.2132, -0.5329);
        const vec3 Bcoeff = vec3(1.1644,  2.1124,  0.000);

        // ???????textureY???textureOut???
        yuv.x = texture2D(textureY, textureOut).r;
        yuv.y = texture2D(textureU, textureOut).r - 0.5;
        yuv.z = texture2D(textureV, textureOut).r - 0.5;

        // ?????rgb
        // ??????
        yuv.x = yuv.x - 0.0625;
        rgb.r = dot(yuv, Rcoeff);
        rgb.g = dot(yuv, Gcoeff);
        rgb.b = dot(yuv, Bcoeff);
        // ?????
        gl_FragColor = vec4(rgb, 1.0);
    }

***

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

**Comment by barry-ran** [comment]
change [UseDesktopOpenGL](https://github.com/barry-ran/QtScrcpy/blob/master/config/config.ini) to 0/1/2
