### ISSUE TITLE
请问有办法用adb命令实现项目中的息屏功能吗？

### ISSUE THREAD

**Issue by zzzop** [barry-ran/QtScrcpy#194]
[https://android.googlesource.com/platform/frameworks/base.git/+/pie-release-2/core/java/android/view/SurfaceControl.java](url)
看到和这个相关，查了谷歌但是我水平不够，不会操作

**Comment by aJIEw** [comment]
`adb shell input keyevent 26`

请善用英文搜索：[how-to-turn-on-and-turn-off-screen-with-adb-command](https://stackoverflow.com/a/41328213/4837812)

**Comment by zzzop** [comment]
> `adb shell input keyevent 26`
> 
> 请善用英文搜索：[how-to-turn-on-and-turn-off-screen-with-adb-command](https://stackoverflow.com/a/41328213/4837812)

这个命令只是模拟电源键，不能达到项目里息屏不锁屏这种效果

**Comment by aJIEw** [comment]
熄屏不锁屏用 adb 应该是做不到的，scrcpy 是用反射来实现这个功能的，通过 `SurfaceControl ` 修改 Display power modes 为 off，参考这个 commit [Implement device screen off while mirroring](https://github.com/Genymobile/scrcpy/commit/12a3bb25d39037931f577dc0165b3e517aad92df#diff-5fde493849f0dc86e0932855ef4266acR86)

**Comment by aJIEw** [comment]
这个 app 似乎可以实现这种功能：[Off without lock](https://play.google.com/store/apps/details?id=com.bryk.off)

**Comment by zzzop** [comment]
> 这个 app 似乎可以实现这种功能：[Off without lock](https://play.google.com/store/apps/details?id=com.bryk.off)

这个软件尝试过，在我手机(xz2 10.0)上不能使用，root模式会锁定/noroot只是显示一张黑色图片。
现在只找到一款软件[https://www.amazon.com/Derp-Developer-Black-Screen-Life/dp/B01BCI1OOE](url)，是依靠手动遮盖距离传感器像接电话一样息屏亮屏，感觉不是很完美。
`SurfaceControl` 这个如果能用root权限修改就好了，不过我也没查到，完全不懂android开发，只好做一个伸手党了

**Comment by aJIEw** [comment]
我也没找到好的实现，这个需求太小众了😂。我能问下你的使用场景是什么吗？

**Comment by barry-ran** [comment]
SurfaceControl满足不了需求吗？

**Comment by zzzop** [comment]
> SurfaceControl满足不了需求吗？

满足，请问能否通过命令行执行这个息屏不锁屏的操作

**Comment by barry-ran** [comment]
> > SurfaceControl满足不了需求吗？
> 
> 满足，请问能否通过命令行执行这个息屏不锁屏的操作

不能，只能通过编程的方式

**Comment by yu-liang-zheng** [comment]
> > > SurfaceControl满足不了需求吗？
> > 
> > 
> > 满足，请问能否通过命令行执行这个息屏不锁屏的操作
> 
> 不能，只能通过编程的方式

https://toutiao.io/posts/r67jk9/preview，“怎么通过adb shell来调用SurfaceControl，答案就是app_process”

**Comment by sunqb** [comment]
> `db shell input keyevent 26`
> 
> 请善用英文搜索：[how-to-turn-on-and-turn-off-screen-with-adb-com](https://stackoverflow.com/a/41328213/4837812)

这个很有用，我们项目里面需要息屏就这么用

**Comment by Typhonling** [comment]
据我所知有2种方式。

1. [adb+DisplayToggle.dex实现手机屏幕关闭但不休眠](https://meta.appinn.net/t/topic/46361)，只需要adb。
2. [开屏伪装|FakeScreen](https://github.com/Xposed-Modules-Repo/me.neversleep.plusplus)，需要Xposed。
