### ISSUE TITLE
能否支持坚果R1,三星、华为的大屏模式呢？

### ISSUE THREAD

**Issue by tchangeme** [barry-ran/QtScrcpy#20]
可以通过一线通接上一个HDMI的欺骗器，启动大屏模式后，在通过无线的方式或其他方式连接到锤子坚果的TNT或三星的DEX模式，那就太牛了。现在有太多人为了使用大屏模式，买了触控屏。但也有很多人喜欢大屏模式，比如TNT，但是已经有笔记本或PC了，如果能用这种方式解决，应该还是很有市场的，哪怕收费，都会有很多人买的呢。

**Comment by barry-ran** [comment]
你在交流群里吗？可否私聊详细讨论下？

**Comment by tchangeme** [comment]
在交流群里呢
