### ISSUE TITLE
Macos mouse is unusable in pubg

### ISSUE THREAD

**Issue by flyingduck234** [barry-ran/QtScrcpy#200]
The horizontal mouse movement is very limited in Macos unless I move it in a quick motion. 

Lowering the speed ratio does help but still has a stop point. 

Any suggestions
Macos 10.15

**Comment by colorlight** [comment]
same problem

**Comment by barry-ran** [comment]
I will test and can you provide a video demo？

**Comment by flyingduck234** [comment]
Thank you berry. I'll provide the video demo. But here is the problem (I think)

When you start the application in the Macos, ~ key grabs the mouse in the game. But the mouse doesn't stick to window. The mouse works well as long as it's inside the window but when it reaches the edge of the window it leave the window.

Starting qtscrcpy with su command using terminal will bind and lock the mouse to the window.
But when it reaches to the edge of the window although it doesn't leave the window the camera movement stops unless you bring back the mouse to the center of the window.

**Comment by barry-ran** [comment]
I know the reason, you don’t need to provide a video anymore, I will fix it

**Comment by ercanezin** [comment]
Hey,

I wrote a small python app that resets the mouse location when it reaches the edge of the monitor. You might need to set these numbers to the appropriate one for yourself.

It might be useful to do the same in CPP.

from pynput.mouse import  Controller, Listener
mouse = Controller()
SCR_RES_X_MAX = 1920
SCR_RES_Y_MAX = 1080
def on_move(x, y):
    print('Pointer moved to {0}'.format((x, y)))
    if x > SCR_RES_X_MAX - 20 or x < 20 or y > SCR_RES_Y_MAX - 20 or y < 20:
        mouse.position = (SCR_RES_X_MAX / 2, SCR_RES_Y_MAX / 2)
        print('mouse position set 960,  540'.format(SCR_RES_X_MAX, SCR_RES_Y_MAX))

with Listener(
        on_move=on_move,
        on_click=on_click) as listener:
    listener.join()

Thanks @barry-ran for the effort. 

Is it possible we change '~' button to middle button on mouse? I think it is better.

Best wishes

**Comment by flyingduck234** [comment]
I just tested the latest release, the issue seems to be resolved. But the mouse movement is not as good as in Windows. Maybe it's just me

**Comment by barry-ran** [comment]
@flyingduck234 I will try to continue to optimize the experience

**Comment by flyingduck234** [comment]
The issue if fixed

**Comment by jshmcv6** [comment]
> Hey,
> 
> I wrote a small python app that resets the mouse location when it reaches the edge of the monitor. You might need to set these numbers to the appropriate one for yourself.
> 
> It might be useful to do the same in CPP.
> 
> from pynput.mouse import Controller, Listener mouse = Controller() SCR_RES_X_MAX = 1920 SCR_RES_Y_MAX = 1080 def on_move(x, y): print('Pointer moved to {0}'.format((x, y))) if x > SCR_RES_X_MAX - 20 or x < 20 or y > SCR_RES_Y_MAX - 20 or y < 20: mouse.position = (SCR_RES_X_MAX / 2, SCR_RES_Y_MAX / 2) print('mouse position set 960, 540'.format(SCR_RES_X_MAX, SCR_RES_Y_MAX))
> 
> with Listener( on_move=on_move, on_click=on_click) as listener: listener.join()
> 
> Thanks @barry-ran for the effort.
> 
> Is it possible we change '~' button to middle button on mouse? I think it is better.
> 
> Best wishes

and how do i input this to work? If i paste this into python it gives me invalid message

**Comment by hocapcm** [comment]
> > Hey,
> > I wrote a small python app that resets the mouse location when it reaches the edge of the monitor. You might need to set these numbers to the appropriate one for yourself.
> > It might be useful to do the same in CPP.
> > from pynput.mouse import Controller, Listener mouse = Controller() SCR_RES_X_MAX = 1920 SCR_RES_Y_MAX = 1080 def on_move(x, y): print('Pointer moved to {0}'.format((x, y))) if x > SCR_RES_X_MAX - 20 or x < 20 or y > SCR_RES_Y_MAX - 20 or y < 20: mouse.position = (SCR_RES_X_MAX / 2, SCR_RES_Y_MAX / 2) print('mouse position set 960, 540'.format(SCR_RES_X_MAX, SCR_RES_Y_MAX))
> > with Listener( on_move=on_move, on_click=on_click) as listener: listener.join()
> > Thanks @barry-ran for the effort.
> > Is it possible we change '~' button to middle button on mouse? I think it is better.
> > Best wishes
> 
> and how do i input this to work? If i paste this into python it gives me invalid message

https://drive.google.com/drive/folders/1PjkfCu_Pua8JKRWeQ5PkwdqpFNaqt4Ls?usp=sharing
Download this and run the file mousereset in a folder named "dist", or you can just run the python code by terminal (Need to install pynput, go to google to check how to do that)
