### ISSUE TITLE
1.4.0仍然存在需要的几个问题

### ISSUE THREAD

**Issue by masterchiang** [barry-ran/QtScrcpy#221]
1，分辨率那个，1080不是真的1080P，以长度来计算1080。而不是宽度
2，触摸位置归位时间应该再短一点，可解决和平精英下车卡视角问题
方案B：新增一种按键，可以当宏吧，按下下车键之后，自动按两下“波浪键”, 就不会卡视角了，亲测，我的鼠标支持编程功能，已经试过了，不会卡视角，相当于重新进入窗口输入模式，让视角触摸点重新归位。除了下车，车上切换座位一样会卡视角，这个时候按两下“波浪键”重新进入控制模式也可以解决。
（切换座位开枪这个请用buggy赛车测试，最明显）

换句话说，需要解决的就是触摸归位时间，或者分别对“下车”，“打开箱子”，“切换座位开火”，“大地图”，“背包窗口”这几个功能进行重新定义按键模式，1.4.0仅仅是在按下这类"switchMap": true种类的按键支持呼出鼠标，同时键盘也能操作而已。没有从根本上解决卡视角问题。
另外，锁定一个方向移动，需要关闭软件重新打开这种情况也还存在的

3，speedratio回报率问题，这个每动一下是2个像素点，而不是一个像素点，会造成控制不准

4，"type": "KMT_DRAG"，这种模拟屏幕滑动，应该新增一个dragspeed的函数上去，设置滑动速度，默认速度我看了下，简直是一瞬间，有些游戏不生效的

@barry-ran

**Comment by Abeelme** [comment]
1.4.0 Any help please ! :)


start server...
AdbProcess::out:/private/var/folders/qg/fpl0j8f520q6_7z51kzj7ztc0000gn/T/AppTranslocation/B370A3B2-BC6F-4F17-9341-94D0068554BF/d/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed. 13.9 MB/s (33142 bytes in 0.002s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException: The server version (1.14) does not match the client (1.12.1)
at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
at com.genymobile.scrcpy.Server.main(Server.java:221)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)

AdbProcess::out:

**Comment by masterchiang** [comment]
特别是开镜的时候，竟然也卡视角，真的特别难受

**Comment by barry-ran** [comment]
> 特别是开镜的时候，竟然也卡视角，真的特别难受

开镜卡视角是什么意思？鼠标右键开镜会影响视角移动？方便录视频看下吗？我这边没出现这个问题

**Comment by 779822364** [comment]
卡方向问题任然存在，我也遇到了。

**Comment by 779822364** [comment]
不清楚是什么原因造成的，触发的几率很低。

**Comment by masterchiang** [comment]
> > 特别是开镜的时候，竟然也卡视角，真的特别难受
> 
> 开镜卡视角是什么意思？鼠标右键开镜会影响视角移动？方便录视频看下吗？我这边没出现这个问题

这个是speedratio问题，开模拟指针发现的，加速度问题，如果甩鼠标过快，而你的speedration又低，那么久容易卡视角。不过这个原因也可能跟上下车视角卡着一个样，需要触摸归位才能解决，就如你说的，可能创建了新的图层

**Comment by masterchiang** [comment]
就是加速度突然很快，然后指针模拟已经到了屏幕边缘了，软件正常的话，就会重置回你设置的锁定视角触摸坐标上，我设置的是x,y=0.5屏幕正中间。这点我看了，训练场测试没发现问题，鼠标加速度很高的情况下，快速转头，指针到达边缘还是会自动回归到中心点后再往该方向继续滑动的，但是实战中有一定概率不会重置到中心点。毕竟实战中可能甩鼠标速度更快

**Comment by masterchiang** [comment]
> 不清楚是什么原因造成的，触发的几率很低。

"switchMap": true  这种按键的，只要你碰到都会，正常下操作不管你怎么按方向键都没事。

如果新增模拟摇杆方式不知道会不会解决，就是给与方向一个加速度，慢慢推至offset所设定的最大值

**Comment by masterchiang** [comment]
> > 特别是开镜的时候，竟然也卡视角，真的特别难受
> 
> 开镜卡视角是什么意思？鼠标右键开镜会影响视角移动？方便录视频看下吗？我这边没出现这个问题

开镜卡视角原因也找到，就是侧头QE的问题，如果开镜的同时按了侧头，那么有大概率会直接卡视角鼠标动不了，推测应该是和上下车一个根源，创建了一个新的图层窗口需要重新触摸屏幕才能滑动，所以你必须要解决触摸归位时间才能解决各种卡视角问题，这个就是根源。



另外，speedratio那个我也要说了，大家都知道的，数值越低，模拟屏幕滑动就越大，就越容易引发各种BUG，打开箱子的时候最明显啦，因为滑动范围大，很容易就划过你不想要的物资帮你捡上去了。

所以speedratio越大越好？那就大错特错了。就是因为上面的移动回报率问题，每移动一下是动两个像素点，而不是一个像素点，因此。speedratio越高的情况下，你也得把游戏速度调高，但是这样一来，会引发一个更严重的问题，因为回报率不高，每移动一下是两个像素点。灵敏度一高了，直接把这个不精准的问题一下放大了。导致高speedratio下，精准度极差。



因此，和平精英上这两个致命问题需要尽快处理。

1.万恶之源，触摸归位时间，或者新增一个函数，让某些按键按下后会重新进入控制模拟，按两下tab上面那个波浪键的效果。


2，speedratio刷新率问题，把每两个像素移动点变成每次一个像素点

**Comment by masterchiang** [comment]
5，第五个BUG补充，正如隔壁还有个老外发帖反馈的问题，窗口大小问题，每次都是自动重置大小，原版现在都能自动保存大小了，这个现在还没同步

**Comment by barry-ran** [comment]
> 5，第五个BUG补充，正如隔壁还有个老外发帖反馈的问题，窗口大小问题，每次都是自动重置大小，原版现在都能自动保存大小了，这个现在还没同步

老外反馈的是新增的两个配置项lockVideoOrientation和stayAwake没有保存到config，没有提窗口大小和位置的事，而且窗口和位置保存功能早就有了

**Comment by barry-ran** [comment]
> speedratio

speedratio不是固定值，是自己在脚本中配置的，具体多少合适需要根据自己的鼠标灵敏度，游戏设置的灵敏度来调节

**Comment by barry-ran** [comment]
> > > 特别是开镜的时候，竟然也卡视角，真的特别难受
> > 
> > 
> > 开镜卡视角是什么意思？鼠标右键开镜会影响视角移动？方便录视频看下吗？我这边没出现这个问题
> 
> 开镜卡视角原因也找到，就是侧头QE的问题，如果开镜的同时按了侧头，那么有大概率会直接卡视角鼠标动不了，推测应该是和上下车一个根源，创建了一个新的图层窗口需要重新触摸屏幕才能滑动，所以你必须要解决触摸归位时间才能解决各种卡视角问题，这个就是根源。
> 
> 另外，speedratio那个我也要说了，大家都知道的，数值越低，模拟屏幕滑动就越大，就越容易引发各种BUG，打开箱子的时候最明显啦，因为滑动范围大，很容易就划过你不想要的物资帮你捡上去了。
> 
> 所以speedratio越大越好？那就大错特错了。就是因为上面的移动回报率问题，每移动一下是动两个像素点，而不是一个像素点，因此。speedratio越高的情况下，你也得把游戏速度调高，但是这样一来，会引发一个更严重的问题，因为回报率不高，每移动一下是两个像素点。灵敏度一高了，直接把这个不精准的问题一下放大了。导致高speedratio下，精准度极差。
> 
> 因此，和平精英上这两个致命问题需要尽快处理。
> 
> 1.万恶之源，触摸归位时间，或者新增一个函数，让某些按键按下后会重新进入控制模拟，按两下tab上面那个波浪键的效果。
> 
> 2，speedratio刷新率问题，把每两个像素移动点变成每次一个像素点

不想通过缩短鼠标重置事件的方式来修复卡视角问题，游戏新建了视图，所以会卡视角，需要手动按两次波浪键解决

**Comment by masterchiang** [comment]
窗口大小保存没有啊，userdata.ini里面的ini文件虽然有提到窗口大小，但是没有任何意义，不起作用。而且方向锁定也是不带保存的。

**Comment by masterchiang** [comment]
speedratio那个真的不骗你，手机2560X1440的分辨率，稍微动一下是以两个像素单位的，如果其他人的手机分辨率越低，那这样下来是不是会造成滑动精度不准呢？我也试过把speedratio调成1了，也调过默认的10，也试过20.无论你横动也好，竖动也好，模拟指针移动始终是以两个像素点为基准的，x=1500,你右动一下就是1502，永远看不到奇数。这已经跟游戏无关了

@barry-ran

**Comment by masterchiang** [comment]
卡视角那个我已经通过鼠标带的宏功能实现自动附加两下波浪键，窗口旋转后会重置大小这个也无所谓了，但是speedratio动一下两个像素点这个问题。


真心希望拜托你了
@barry-ran

**Comment by masterchiang** [comment]
补充一下情报，自从你的1.3.6改进后，我就把原版scrcpy丢去吃灰了，今天试了下原版的scrcpy发现模拟指针运动也是精准的，动一下就是一个像素点，你的qtscrcpy不管是按下波浪键进入控制模式，还是用鼠标点击滑动屏幕方式。指针运动始终是以2个像素点运动。这个跟speedratio无关了，是软件参数设置问题了。我已经换了几台手机试过了。

@barry-ran

**Comment by barry-ran** [comment]
> 补充一下情报，自从你的1.3.6改进后，我就把原版scrcpy丢去吃灰了，今天试了下原版的scrcpy发现模拟指针运动也是精准的，动一下就是一个像素点，你的qtscrcpy不管是按下波浪键进入控制模式，还是用鼠标点击滑动屏幕方式。指针运动始终是以2个像素点运动。这个跟speedratio无关了，是软件参数设置问题了。我已经换了几台手机试过了。
> 
> @barry-ran

怎么验证的指针是一个像素还是两个像素？我记得即使用手指直接拖动，拖动快了也是间隔多个像素点啊，不可能每个像素点都触摸到啊

**Comment by barry-ran** [comment]
> speedratio那个真的不骗你，手机2560X1440的分辨率，稍微动一下是以两个像素单位的，如果其他人的手机分辨率越低，那这样下来是不是会造成滑动精度不准呢？我也试过把speedratio调成1了，也调过默认的10，也试过20.无论你横动也好，竖动也好，模拟指针移动始终是以两个像素点为基准的，x=1500,你右动一下就是1502，永远看不到奇数。这已经跟游戏无关了
> 
> 好比显示器的逐行扫描和隔行扫描一样，损失一半的精确度
> 
> @barry-ran

这个精度有什么用呢？从A点拖到B点，假设有四个像素1，2，3，4，按照1，2，3，4的方式触摸和按照1，4的方式触摸，效果有什么区别吗？

**Comment by masterchiang** [comment]
这个很简单啊，入你的FAQ上面说的，开发者模式中打开那个“指针位置”，上面能看到按下鼠标后的模拟点击X和Y的坐标对吧，然后你按下去拖动后，会发现动一下是两个像素点。拿x轴来说，水平稍微向右动一下，x=1500就会变成x=1502，不会变成1500的，而原版scrcpy，是铁定1501的。猜测可能你封装过程中qt覆盖了参数。这个精度很重要的哦，如你所说的，1.2,3,4.5,6，动一下像素1直接跳过像素2，变到3，再动一下直接跳过4变成5.
运动轨迹就是1,3,5，直接跳过2,4。也有可能跟你设置的回报率有关。

这样一来，控制精准度就差了足足一倍了。

**Comment by barry-ran** [comment]
> 这个很简单啊，入你的FAQ上面说的，开发者模式中打开那个“指针位置”，上面能看到按下鼠标后的模拟点击X和Y的坐标对吧，然后你按下去拖动后，会发现动一下是两个像素点。拿x轴来说，水平稍微向右动一下，x=1500就会变成x=1502，不会变成1500的，而原版scrcpy，是铁定1501的。猜测可能你封装过程中qt覆盖了参数。这个精度很重要的哦，如你所说的，1.2,3,4.5,6，动一下像素1直接跳过像素2，变到3，再动一下直接跳过4变成5.
> 运动轨迹就是1,3,5，直接跳过2,4。也有可能跟你设置的回报率有关。
> 
> 这样一来，控制精准度就差了足足一倍了。
> @barry-ran

精度是差了一倍，然后到底有什么问题呢？在什么场景下会需要这个精度？由于这个精度不准会造成什么问题？

**Comment by masterchiang** [comment]
这个精度对于MMORPG游戏，策略游戏等，确实没什么影响，甚至一点事都没，但是对于那些按钮特别小的，或者像射击类游戏的，这个精度直接体现出巨大差距。

打个比方

上面说了动一下2个像素点，假如我鼠标动个1毫米就会触发，那么正常情况下我的准星就会移动一个像素点，屏幕AB两点距离假如400个像素点。从屏幕A点拖动到屏幕B点，我就需要把鼠标移动个40厘米左右对吧，如果精度不准的话，只需要移动大概20多厘米就到了。这样一来，和你的对鼠标操控的手感就会引来巨大的差异。让你产生各种怀疑

关键为什么是20多厘米而不是20厘米呢，因为这根本不稳定的，低速下运动是肯定每动一下两个像素点，高速乱拖动下偶然会产生奇数运动点，
x=1500右动正常会这样运动的1502,1504,1506,1508,x+2的函数一样

高速下运动，
x=1500，快速拖到1756这个附近，有可能变成1755，而不是变成1756或者1754、但是概率很低。

你可以试下的，原版没有这个问题，用QT封装后就这样了，其中过程肯定有什么数据覆盖掉了

@barry-ran

**Comment by masterchiang** [comment]
@barry-ran 还不明白的话，用生活常识啦，假如我要画一个圆，接着我不说什么你都知道这样子画下去会怎么样，它会不会很“圆”

**Comment by masterchiang** [comment]
@barry-ran 原因今天也找到了，原版也是有这种问题，上次没找到问题，是因为原版开的分辨率比较高，QT开的1280X720.

是缩放问题导致的像素点不准确。

例如手机分辨率2560X1440,如果你开的1280X720模式的话，动一下就是两个像素点。
当你手机降低分辨率设置为1920X1080，而在QT和原版也是开的1920X1080分辨率的话，那么鼠标滑动也是每动一下一个像素点。这个应该是缩放问题导致的。需要找原版作者解决了

**Comment by mwmb2** [comment]
这个帖子都看完了，很专业和精彩！
