### ISSUE TITLE
v1.3.6  Works Fine But  v1.4.0 Show me this Error!

### ISSUE THREAD

**Issue by Abeelme** [barry-ran/QtScrcpy#222]
start server...
AdbProcess::out:/private/var/folders/qg/fpl0j8f520q6_7z51kzj7ztc0000gn/T/AppTranslocation/B370A3B2-BC6F-4F17-9341-94D0068554BF/d/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed. 13.9 MB/s (33142 bytes in 0.002s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException: The server version (1.14) does not match the client (1.12.1)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)

AdbProcess::out:

**Comment by masterchiang** [comment]
clean the file fold，dont unzip cover the 1.3.6, build it alone ,just you see,

AdbProcess::error:java.lang.IllegalArgumentException: The server version (1.14) does not match the client (1.12.1)

**Comment by masterchiang** [comment]
and remember .taskman finished the adb.exe first

**Comment by masterchiang** [comment]
sorry,could not see you client is mac it seems mac 1.4.0 have a big crash problem,suggest you stay in 1.3.6 wait author fix it

**Comment by Abeelme** [comment]
> sorry,could not see you client is mac it seems mac 1.4.0 have a big crash problem,suggest you stay in 1.3.6 wait author fix it

Thank you so much !

**Comment by barry-ran** [comment]
update mac dmg [v1.4.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.4.0), try it!

**Comment by Abeelme** [comment]
> update mac dmg [v1.4.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.4.0), try it!

Yes it's working now thank you a lot for fast update ! 
But the problem of mouse is still :( 
how can i fix please?

**Comment by barry-ran** [comment]
> > update mac dmg [v1.4.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.4.0), try it!
> 
> Yes it's working now thank you a lot for fast update !
> But the problem of mouse is still :(
> how can i fix please?

What is the problem with the mouse? Can you describe it in detail？
