### ISSUE TITLE
无线连接问题

### ISSUE THREAD

**Issue by barry66030** [barry-ran/QtScrcpy#225]
请教一下无线连接部份，Android设备假如重新开机后就无法再无线连接了，要重新USB数据线连接后才可以重新使用无线方式做连线.....
是否有方法处理呢?(Android设备没ROOT的情况下....)

**Comment by barry-ran** [comment]
可以在手机端安装terminal软件，开启adbd，获取ip，就可以无线连接了

**Comment by barry66030** [comment]
感谢回复~~还一個问题，已经可成功无线连接，我有连接多台Android设备，但是过一段时间输入指令adb devices查看连接的设备有些正常但有些会显示offline，而造成无法无线连接，请问是什么问题呢?因为Android网路状态一直都有连线没休眠，connect IP也是连的到，但就是显示offline...

**Comment by WrathGluttony** [comment]
> 可以在手机端安装terminal软件，开启adbd，获取ip，就可以无线连接了

作者，您好，我资质愚钝，您的这句话没看懂。
①手机端安装哪个terminal APP?开启adbd是在terminal APP上开启？还是在QtScrcpy这个软件上开启？获取IP是在terminal APP上获取？还是在QtScrcpy软件上获取？
②第1次必须用USB线连接手机（手机端打开USB调试、打开开发者模式），第1次成功后，按照您说的“可以在手机端安装terminal软件，开启adbd，获取ip，就可以无线连接了”之后，重启电脑、重启手机，都无需连接USB线了，每次都可以直接 无线连接了，是吗？手机端还用每次都打开USB调试、打开开发者模式吗？

**Comment by WrathGluttony** [comment]
> 可以在手机端安装terminal软件，开启adbd，获取ip，就可以无线连接了

①从Google Play上下载最新版的Terminal Emulator for Android（1.0.70），输入如下4行命令，但是不成功，输入第1个u就出错：
su
setprop service.adb.tcp.port 5555
stop adbd
start adbd
②输入第1个u后，结果如下（是因为手机没root吗？） ：
:/ $ su
/system/bin/sh: su: inaccessible or not found
127|:/ $
③按说输入上面4行命令就可以了，但是输入第1个u就出错了

**Comment by WrathGluttony** [comment]
①进入模拟器shell后，报/system/bin/sh: su: inaccessible or not found，是因为下载的模拟器是带Google play版的，没有root用户，需下载带Android Api版本的
如图：
![image](https://user-images.githubusercontent.com/50478981/155528010-fefd5102-ce9f-43fe-a85b-e6d3607da452.png)
②请问到哪里下载“带Android Api版本的”terminal emulator for android这款APP?

**Comment by WrathGluttony** [comment]
今天就碰到了这么一个报错。我把他的解决。方法给记录下来，帮助后来的人。希望大家多多关注我的公众号，支持我。
D:\adb>adb shell
picasso:/ $ su
/system/bin/sh: su: inaccessible or not found
127|picasso:/ $

运行cmd 窗口下adb shell 命令，adb shell之后su无法转到root权限
这样的情况下怎么办呢？网络上面的解决办法实在是列举的太多了，我们只需要尝试其中的一种就行了。
解决方法：
---
解决方法：因为操作系统本来就没有添加root用户，需要下载一个一键root来生成root用户；下了个，安装后，运行一键root；再运行 su，果然好使了，变成 # 了
----
解决方法：Android Studio带(Google Play)的模拟器无法获得root权限安装
该换成为带(Google APIs)的模拟器即可

**Comment by WrathGluttony** [comment]
> ①手机端安装哪个terminal APP?开启adbd是在terminal APP上开启？还是在QtScrcpy这个软件上开启？获取IP是在terminal APP上获取？还是在QtScrcpy软件上获取？
> ②第1次必须用USB线连接手机（手机端打开USB调试、打开开发者模式），第1次成功后，按照您说的“可以在手机端安装terminal软件，开启adbd，获取ip，就可以无线连接了”之后，重启电脑、重启手机，都无需连接USB线了，每次都可以直接 无线连接了，是吗？手机端还用每次都打开USB调试、打开开发者模式吗？
③打搅了，谢谢

**Comment by WrathGluttony** [comment]
> 感谢回复~~还一個问题，已经可成功无线连接，我有连接多台Android设备，但是过一段时间输入指令adb devices查看连接的设备有些正常但有些会显示offline，而造成无法无线连接，请问是什么问题呢?因为Android网路状态一直都有连线没休眠，connect IP也是连的到，但就是显示offline...
@barry66030 
①手机端安装哪个terminal APP?开启adbd是在terminal APP上开启？还是在QtScrcpy这个软件上开启？获取IP是在terminal APP上获取？还是在QtScrcpy软件上获取？
②第1次必须用USB线连接手机（手机端打开USB调试、打开开发者模式），第1次成功后，按照您说的“可以在手机端安装terminal软件，开启adbd，获取ip，就可以无线连接了”之后，重启电脑、重启手机，都无需连接USB线了，每次都可以直接 无线连接了，是吗？手机端还用每次都打开USB调试、打开开发者模式吗？
③打搅了，谢谢
