### ISSUE TITLE
some problem in real applications.

### ISSUE THREAD

**Issue by dfc643** [barry-ran/QtScrcpy#226]
very big thanks to developer for build the truly awesome tool.

there are some problem found in real applications.
1. huge latency (not sync) when device over than 3. 
    ```
    * connected via USB 2.0 on motherboard.
    * display synced when minimize and restore all window.
    ```
2. sometimes, toolbar not following the window.
3. wireless adb disconnect only working with port 5555.
4. some option not saved, (keep awake, orientation lock)

and here are some suggestion.
1. wireless connection without adb (via client side app)
    ```
    because wireless adb is unstable, in application over internet.
    ```
2. back action for mouse right click.

**Comment by masterchiang** [comment]
suggest you buy a usb 3.0 cable,but many phone still stay at USB2.0,whatever those phone is newest.likes all vivo,oppo,xiao mi.all series USB2.0.

samsung,HUAWEI,moto,LG is USB3.0 upper.
but you need to test your phone is really support USB3.0?
check your charge cable,

USB2.0 MAX speed 35m/s,USB3.0 more than 400m/s

usb3.0 can work on 200M rate, 1920 or origin .

USB2.0 must be lag

**Comment by dfc643** [comment]
> suggest you buy a usb 3.0 cable,but many phone still stay at USB2.0,whatever those phone is newest.likes all vivo,oppo,xiao mi.all series USB2.0.
> 
> samsung,HUAWEI,moto,LG is USB3.0 upper.
> but you need to test your phone is really support USB3.0?
> check your charge cable,
> 
> USB2.0 MAX speed 35m/s,USB3.0 more than 400m/s
> 
> usb3.0 can work on 200M rate, 1920 or origin .
> 
> USB2.0 must be lag
> 
> other question, author was already known,
> 
> window option should be saved at config.ini file

thank you for reply. this is a very nice tool.
