### ISSUE TITLE
Visual prompt for simulated click position 模拟点击位置可视化提示

### ISSUE THREAD

**Issue by du33169** [barry-ran/QtScrcpy#238]
Every time you change the click position, you have to try a lot of times,
And turning on the "touch display" switch didn't work either.
Can you add an option to show all the points?
每次改点位都要盲目尝试很多遍
而且打开“触摸显示”开关也并不起作用

可以增加一个显示所有点位的选项吗（参考网易uu模拟器）

**Comment by barry-ran** [comment]
v1.4.0版本会在控制台输出pos，不用盲目尝试了
```
"pos": {"x": 0.37551, "y": 0.322382}
```
