### ISSUE TITLE
新增codec options指令可减少至少一倍延迟

### ISSUE THREAD

**Issue by masterchiang** [barry-ran/QtScrcpy#245]
scrcpy v1.14 的更新说明上提到了一处
Add --codec-options to pass MediaFormat options directly
原文链接[https://github.com/Genymobile/scrcpy/pull/1325](url)

coder-options源码在此[https://github.com/Genymobile/scrcpy/commit/080a4ee3654a9b7e96c8ffe37474b5c21c02852a](url)

scrcpy 命令格式为--codec-options profile=1,level=1
用命令行scrcpy.exe --help
cmd /k echo

可以查到相关参数

其中level可选范围如下

[https://developer.android.com/reference/android/media/MediaCodecInfo.CodecProfileLevel#profile](url)
每个数值对应不一样的编码压缩方式，这个请务必开放给使用者自行填入，每台手机都不一样的，有些人1好用，有些人1024好用
（实测感觉没变化）

显著降低延迟的是这个profile里面定义的内容，只有1可用，2等于没加上去一样

另外也许可以再在原版的基础上，对FFMPEG,X264的编码器上再增加一条CODEC_FLAG_LOW_DELAY 和qmin,qmax，新增一个UI选项，让画面质量可选低中高。
参考这里[https://www.cnblogs.com/wanggang123/p/6346787.html](url)
[https://developer.android.com/reference/android/media/MediaFormat#KEY_LOW_LATENCY](url)

这个InitEncoderCodec 查了下源码，里面好像没有的

另外说明一下，码率高了可以弥补level压缩导致的画面缩水，目前不清楚到底是码率占用资源高一点还是level压缩占用资源高。这两个都是互补缺陷的

另外，方向锁定这个希望可以写入到config读取，让其每次打开软件都不变。因为每次方向一自动旋转，窗口大小和位置就会重置

**Comment by barry-ran** [comment]
[v1.4.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.4.1)
