### ISSUE TITLE
qtscrcpy1.4.1最新版本运行时提示由于找不到MSVCP140_1.dll,无法执行代码

### ISSUE THREAD

**Issue by ZihaoXingUP** [barry-ran/QtScrcpy#250]
qtscrcpy1.4.1最新版本运行时提示由于找不到MSVCP140_1.dll,无法执行代码

**Comment by wangwhc** [comment]
同样的错误，求解。

**Comment by hachiko008** [comment]
uninstall the current vcredistributables you have then download and install this one. its a 2015-2019 compiled version.

https://download.visualstudio.microsoft.com/download/pr/d60aa805-26e9-47df-b4e3-cd6fcc392333/7D7105C52FCD6766BEEE1AE162AA81E278686122C1E44890712326634D0B055E/VC_redist.x64.exe

**Comment by Leon406** [comment]
下载MSVCP140_1.dll,放到应用根目录即可

**Comment by barry-ran** [comment]
v1.4.5 ok
