### ISSUE TITLE
Black screen in some devices

### ISSUE THREAD

**Issue by hachiko008** [barry-ran/QtScrcpy#257]
I have almost two (2) devices connected after this software executed that displays black screen and never had any used single feature. I hope im not the only one around here. 

![image](https://user-images.githubusercontent.com/68344701/87632375-d9ef7b00-c76b-11ea-92a6-e813c2804a44.png)

![image](https://user-images.githubusercontent.com/68344701/87632655-61d58500-c76c-11ea-8b40-8e02e97adffd.png)

**Comment by hachiko008** [comment]
well after doing some research, everythings fine now

**Comment by beshoo** [comment]
how did you solve the problem @hachiko008 i am on smasung A50 and i have black screen as you did

**Comment by hachiko008** [comment]
@beshoo try to change UseDesktopOpenGL=1/2 on config.ini
