### ISSUE TITLE
请求优化下无线连接的体验

### ISSUE THREAD

**Issue by Vixb1122** [barry-ran/QtScrcpy#269]
1. 提供下拉框，支持选择最近几次连接的 IP 地址
2. 输入框中默认填充最近一次连接的 IP 地址
![优化无线连接](https://user-images.githubusercontent.com/17810492/90237997-ceb96900-de57-11ea-9b14-7ba4e7900506.png)

**Comment by Fawkes-hub** [comment]
支持，重启软件之后，连接都需要手动输入IP，比较麻烦

**Comment by msnh2012** [comment]
Please check out #385

**Comment by barry-ran** [comment]
[v1.6.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.6.0)

**Comment by Vixb1122** [comment]
@barry-ran 该提交并未覆盖这个问题啊，断开连接后，还是要手动输入ip。
