### ISSUE TITLE
90HZ高帧率下界面刷新延迟

### ISSUE THREAD

**Issue by Plihuo** [barry-ran/QtScrcpy#273]
跳帧Bug在处理当前跳帧的时候如果当前有绘制的帧则跳过，如果当前没有绘制的帧则相反！！！

previousFrameSkipped = !m_renderingFrameConsumed这段代码改成
previousFrameSkipped = m_renderingFrameConsumed这个问题就OK了！！！！

**Comment by barry-ran** [comment]
不用改代码，在config.ini中修改是否渲染过期帧即可
