### ISSUE TITLE
没装vs2015的电脑上会缺少dll，建议将用到的vs动态链接库打包进压缩包

### ISSUE THREAD

**Issue by coreur** [barry-ran/QtScrcpy#274]
![image](https://user-images.githubusercontent.com/20869550/91250960-d7316e00-e78c-11ea-93fe-34eaf4c27d8d.png)

[vcruntime140_1 .zip](https://github.com/barry-ran/QtScrcpy/files/5127380/vcruntime140_1.zip)

**Comment by barry-ran** [comment]
[v1.5.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.5.0)
