### ISSUE TITLE
Push 2.0mb/s ADB

### ISSUE THREAD

**Issue by hugonh** [barry-ran/QtScrcpy#283]
Hi guys. i was facing a problem playing mainly pubg mobile with QtScrcpy and never went to higher than 3.0mb/s when i started started server and with this i could barely play and never play pubg on ultra, now i got fixed. And my QtScrcpy is running at 50mb/s. I would like to know how can i pull these files and change on QtScrcpy. Thanks!

**Comment by barry-ran** [comment]
Look at pr as if you changed adb? Can you describe what specific changes have been made to increase to 50m/s?

**Comment by hugonh** [comment]
I did Chocolatey(choco powershell) in Windows.
"Choco install adb" and "Choco upgrade adb" that downloaded newest version for adb like "platform-tools" and i have changed to QtScrcpy-win-x64-v1.4.2 folder these files "Adb.exe" "AdbWinApi.dll "AdbWinUsbApi". It's important for everyone has installed AdbDriverInstaller, it's a tool that update "Android Composite Device". It may helps and 22mb file from Runtime redistributable compilation.

**Comment by Andersonfeng** [comment]
Thanks @hugonh 

It solve my issue
I play pugb with QtScrcpy but sometimes meet 'cut off' issue
It mainly reflect QtScrcpy screen does not move but phone's screen shows normal

I think it due to slow transmission rate

**Comment by hugonh** [comment]
Im glad to help, i did many effort to fix it!

**Comment by barry-ran** [comment]
I will update the latest adb later, sorry to reply so late

**Comment by barry-ran** [comment]
[v1.5.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.5.0)
