### ISSUE TITLE
加一个托盘栏图标，运行点击关闭后隐藏到托盘栏，而不是直接退出

### ISSUE THREAD

**Issue by HaujetZhao** [barry-ran/QtScrcpy#288]
新 feature 请求：加一个托盘栏图标，加一个“点击关闭时隐藏到托盘栏”选项。

**Comment by msnh2012** [comment]
Please check out #385

**Comment by barry-ran** [comment]
[v1.6.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.6.0)
