### ISSUE TITLE
有没有考虑增加给设备序列号起别名的机制?

### ISSUE THREAD

**Issue by hick** [barry-ran/QtScrcpy#294]
我日常只是俩三个机器, 不过只看界面, 经常不记得那个设备序列号对应哪个手机.

有没有考虑过增加给设备号起别名的机制?  比如就现在的序列号那里, 以 序列号+别名 的方式显示即可, 没有别名的不显示.

**Comment by newsfancolaice** [comment]
的确需要这个功能，更便于使用，希望考虑一下

**Comment by msnh2012** [comment]
Please check out #385

**Comment by barry-ran** [comment]
[v1.6.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.6.0)
