### ISSUE TITLE
"switchMap": true 用鼠标按键释放鼠标指针不生效

### ISSUE THREAD

**Issue by Andersonfeng** [barry-ran/QtScrcpy#297]
{
			"comment": "显示鼠标",
			"type": "KMT_CLICK",
			"key": "XButton1",
			"pos": {
				"x": 0.91,
				"y": 0.33
			},
			"switchMap": true
		},

想点击鼠标侧键释放鼠标,可只达到点击效果,并没有释放出鼠标

{
			"comment": "显示鼠标",
			"type": "KMT_CLICK",
			"key": "Key_N",
			"pos": {
				"x": 0.91,
				"y": 0.33
			},
			"switchMap": true
		},

改用键盘按键就可以成功释放出鼠标

**Comment by Andersonfeng** [comment]
用了个折中的办法,设置热键为日常不影响操作的按键,并用鼠标宏代替点击键盘按键
### 设置键盘的某个按键显示鼠标,这里用Control,因为日常点击这个键不影响使用
{
			"comment": "显示鼠标",
			"type": "KMT_CLICK",
			"key": "Key_Control",
			"pos": {
				"x": 0.50,
				"y": 0.50
			},
			"switchMap": true
		}

### autohotkey设置
;点击鼠标后退键 等同于点击一下键盘 Control键(和平精英显示鼠标)
~XButton1::
Send {Control}
return


### 和平精英卡视角的方法也可以用这个方法 QtScrccpy中设置Insert键为切换脚本
"switchKey": "Key_Insert",

### autohotkey设置
;点击鼠标前进键 等同于点击2下键盘(解决和平精英锁视角)
~XButton2::
Send , {Insert}
Sleep, 10
Send , {Insert}
return

作者辛苦, 项目十分nice

在和平精英中
鼠标按键不能显示鼠标
按键会卡视角

要是这两个问题能解决就太棒了!

**Comment by Andersonfeng** [comment]
用了个折中的办法,设置热键为日常不影响操作的按键,并用鼠标宏代替点击键盘按键
### 设置键盘的某个按键显示鼠标,这里用Control,因为日常点击这个键不影响使用
{
			"comment": "显示鼠标",
			"type": "KMT_CLICK",
			"key": "Key_Control",
			"pos": {
				"x": 0.50,
				"y": 0.50
			},
			"switchMap": true
		}

### autohotkey设置
;点击鼠标后退键 等同于点击一下键盘 Control键(和平精英显示鼠标)
~XButton1::
Send {Control}
return


### 和平精英卡视角的方法也可以用这个方法 QtScrccpy中设置Insert键为切换脚本
"switchKey": "Key_Insert",

### autohotkey设置
;点击鼠标前进键 等同于点击2下键盘(解决和平精英锁视角)
~XButton2::
Send , {Insert}
Sleep, 10
Send , {Insert}
return

作者辛苦, 项目十分nice

在和平精英中
鼠标按键不能显示鼠标
按键会卡视角

要是这两个问题能解决就太棒了!

**Comment by scruel** [comment]
这个 switchMap 到底是啥意思，怎么完全没懂啊？没接触过和平精英
