### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by CXido** [barry-ran/QtScrcpy#30]
建议做一个选项去处边框（这个软件很低的延迟和流畅度真的是很好，但是直播的话会有个大边框）
建议做一个设置保存（因为每次打开软件都要重新设置更高的码率分辨率）
开放更高的码率（这个我觉得可做可不做233）

**Comment by RyanFu** [comment]
请问单客户端最多支持16台手机是基于什么原因确认的？

**Comment by barry-ran** [comment]
非常感谢反馈，很好的建议，后期会处理掉

**Comment by barry-ran** [comment]
相关功能已经增加
