### ISSUE TITLE
延迟投屏延迟比Scrcpy高

### ISSUE THREAD

**Issue by Andersonfeng** [barry-ran/QtScrcpy#304]
玩游戏时有明显的操作延迟
同时开着QtScrcpy和Scrcpy 对比很明显
即使将QtScrcpy比特率调到2000000 尺寸640 延迟依旧

![QQ截图20201015183520](https://user-images.githubusercontent.com/13361365/96113759-369f3500-0f17-11eb-8499-eeffec717178.png)

多次重启QtScrcpy 会有明显改善
不知道什么原因

**Comment by Andersonfeng** [comment]
找到疑似的原因了

connect(this, &VideoSocket::readyRead, this, &VideoSocket::onReadyRead);
查了一些资料发现 客户端readyRead和server端的write不是一一对应的,有时候server端发几次数据client才收到一次,
而且当发送数据量大时,client端接受的字节数好像和server端发送的对不上?

不知道这里改成阻塞的socket会不会有改善?

不好意思 不懂C++和视频渲染...

**Comment by Andersonfeng** [comment]
找到原因了,是recvPacket后 
pushPacket 处理buffer没结束
导致onreadyread没有新的buffer可以read

学习一下看看pushPacket能不能更快处理完

**Comment by Andersonfeng** [comment]
再具体点的原因是avcodec_send_packet()这个方法耗时比较长
也就是解码的方法耗时长了

但是scrcpy并没有这样的问题,
于是更新了一下和ffmpeg有关的几个dll
avcodec-58.dll avformat-58.dll avutil-56.dll swresample-3.dll swscale-5.dll
问题得到改善

2020.9.18 zeranoe 的build ffmpeg网站关闭了,之后只能到其他地方下载ffmpeg的build package了
比如
https://www.gyan.dev/ffmpeg/builds/packages/

**Comment by lucassmoita** [comment]
你解决了吗？如果是的话，你能用视频或其他东西解释一下吗？

**Comment by Andersonfeng** [comment]
> 你解决了吗？如果是的话，你能用视频或其他东西解释一下吗？

1年多没用过了,不好意思
root cause就是画面数据多了来不及解码
但是操作线程是没什么延迟的
也就是说可以看着屏幕玩而不是投屏画面
