### ISSUE TITLE
Ubuntu Build Error.

### ISSUE THREAD

**Issue by AGou-ops** [barry-ran/QtScrcpy#308]
The error as follow:
```
......
../../QtScrcpy-1.4.5/QtScrcpy/dialog.cpp: In member function ‘void Dialog::execAdbCmd()’:
../../QtScrcpy-1.4.5/QtScrcpy/dialog.cpp:140:78: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
     m_adb.execute(ui->serialBox->currentText().trimmed(), cmd.split(" ", Qt::SkipEmptyParts));
                                                                              ^~~~~~~~~~~~~~
Makefile:953: recipe for target 'dialog.o' failed
make[1]: Leaving directory '/home/agou-ops/Downloads/build-all-Desktop-Release/QtScrcpy'
make[1]: *** [dialog.o] Error 1
make: *** [sub-QtScrcpy-make_first] Error 2
Makefile:44: recipe for target 'sub-QtScrcpy-make_first' failed
10:39:58: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project all (kit: Desktop)
When executing step "Make"
```

QTCreator Version: 4.5.2 and my Build option is release.  

How should I fix it?

**Comment by marcussacana** [comment]
Here is what I did:
Changed all `Qt::SkipEmptyParts` to `QString::SplitBehavior::SkipEmptyParts`
Changed all `position()` to `posf()` (not sure if is rigth anyway)

Anyway my build binary: [QtScrcpy.zip](https://github.com/barry-ran/QtScrcpy/files/5506972/QtScrcpy.zip)

**Comment by AGou-ops** [comment]
> Here is what I did:
> Changed all `Qt::SkipEmptyParts` to `QString::SplitBehavior::SkipEmptyParts`
> Changed all `position()` to `posf()` (not sure if is rigth anyway)
> 
> Anyway my build binary: [QtScrcpy.zip](https://github.com/barry-ran/QtScrcpy/files/5506972/QtScrcpy.zip)
> As a extra, a version with small changes: [QtScrcpy Linux Custom.zip](https://github.com/barry-ran/QtScrcpy/files/5507037/QtScrcpy.Linux.Custom.zip)

It works!!! Thank u.

**Comment by firstuanl** [comment]
QtScrcpy/util/mousetap/xmousetap.cpp:34: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
../../QtScrcpy_1.4.5/QtScrcpy/util/mousetap/xmousetap.cpp:34:57: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
             if (!*grab_window || gg->width * gg->height <= *grab_window_size) {
                                                         ^

这个图错要怎处理，你好

**Comment by mwmb2** [comment]
> Here is what I did:
> Changed all `Qt::SkipEmptyParts` to `QString::SplitBehavior::SkipEmptyParts`
> Changed all `position()` to `posf()` (not sure if is rigth anyway)
> 
> Anyway my build binary: [QtScrcpy.zip](https://github.com/barry-ran/QtScrcpy/files/5506972/QtScrcpy.zip)
> As a extra, a version with small changes: [QtScrcpy Linux Custom.zip](https://github.com/barry-ran/QtScrcpy/files/5507037/QtScrcpy.Linux.Custom.zip)

我直接运行你的包，提示
./QtScrcpy: symbol lookup error: ./QtScrcpy: undefined symbol: _ZdlPvm, version Qt_5
我已经安装QTCreator。是什么原因呢？

**Comment by marcussacana** [comment]
Try the second build, if not work try install the lastest QT sdk
also, use english.

**Comment by mwmb2** [comment]
> Try the second build, if not work try install the lastest QT sdk
> also, plz, use english.

Both builds have same output as I posted.
I am running Ubuntu 20.04 with QT 5.12.8 installed.  Does the error message mean there's something wrong with QT library link?

**Comment by marcussacana** [comment]
https://stackoverflow.com/questions/61384686/why-symbol-lookup-error-undefined-symbol-when-the-symbol-exists

**Comment by marcussacana** [comment]
also, maybe this?
https://github.com/OneMoreGres/qtc-cppcheck/issues/36#issuecomment-344654116

**Comment by BobbyWibowo** [comment]
> I am running Ubuntu 20.04 with QT 5.12.8 installed (APT installation).

@mwmb2 I'm also on Ubuntu 20.04, and could build this project just fine (tested and running well with my Android 10 phone as well, including the whole custom key mapping memes).

If you still have issues with this, install QtCreator from the official online installer instead of APT: https://www.qt.io/download-open-source. Just choose open-source license on the installer, and you won't have to pay or subscribe to anything. Though you do need to make a Qt account. With this method, you can then have access to the latest QtCreator and Qt **5.15.x**.

Do note that this project specifically requires Qt 5.15.x, so you actually already failed the requirements in the first place.
> 1. Set up the Qt development environment on the target platform (Qt == **5.15.0**, vs == 2017 (mingw not supported))

https://github.com/barry-ran/QtScrcpy#build

**Comment by mwmb2** [comment]
@BobbyWibowo, Thanks for your information. After installing the latest QT with the online installer, I could build it successfully.

**Comment by renanwp2** [comment]
Reverting the patch I commented, it will build successfully on Ubuntu and Debian systems. Of course, I dont know the consequences of it. Hahaha

**Comment by longzhao1996** [comment]
> `QtScrcpy/util/mousetap/xmousetap.cpp:34: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare] ../../QtScrcpy_1.4.5/QtScrcpy/util/mousetap/xmousetap.cpp:34:57: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare] if (!*grab_window || gg->width * gg->height <= *grab_window_size) { ^`
> 
> 这个图错要怎处理，你好

你好，请问这个问题解决了么？

**Comment by barry-ran** [comment]
use Qt 5.15.2, [ci](https://github.com/barry-ran/QtScrcpy/actions) is good
