### ISSUE TITLE
请问支持像华为那样直接拖拽文件么？

### ISSUE THREAD

**Issue by fgheng** [barry-ran/QtScrcpy#31]
rt，请问是否可以直接在电脑和手机之间拖拽文件呢？以及是否支持共享剪切板呢？

**Comment by barry-ran** [comment]
目前可以将文件直接从电脑拖拽到手机，反之不行
剪切板也有间接同步，例如设备中复制以后，电脑中按下Ctrl+C，然后电脑中粘贴，即可看到设备剪切板的内容了

**Comment by wwdok** [comment]
还是很期望能有长按鼠标右键拖拽安卓中的文件到电脑上的功能
