### ISSUE TITLE
为什么还是需要按照 手机上的键盘才能输入 内容

### ISSUE THREAD

**Issue by ruixule** [barry-ran/QtScrcpy#310]
为什么还是需要按照 手机上的键盘才能输入 内容？
建议手机键盘和电脑键盘进行一个映射

**Comment by is-hejun** [comment]
你可下载谷歌输入法，就可以直接在电脑键盘上输入了

**Comment by ruixule** [comment]
我下载了还是不行呀发自我的华为手机-------- 原始邮件 --------发件人： is-hejun <notifications@github.com>日期： 2020年11月9日周一 17:16收件人： barry-ran/QtScrcpy <QtScrcpy@noreply.github.com>抄送： ruixule <1414100586@qq.com>, Author <author@noreply.github.com>主    题： Re: [barry-ran/QtScrcpy] 为什么还是需要按照 手机上的键盘才能输入 内容 (#310)

你可下载谷歌输入法，就可以直接在电脑键盘上输入了

**Comment by ruixule** [comment]
> 你可下载谷歌输入法，就可以直接在电脑键盘上输入了

这个是谷歌输入法， 是在给电脑上下载 还是安卓手机的下载

**Comment by is-hejun** [comment]
在手机上安装Gboard，也就是谷歌输入法，然后点进去将原来的输入法替换为Gboard。使用QTscrcpy时，建议使用Gboard的拼音26键，之后就可以正常输入中文了

**Comment by barry-ran** [comment]
看faq

**Comment by luanshang** [comment]
> 你可下载谷歌输入法，就可以直接在电脑键盘上输入了

那下载了怎么还要使用，我不想更改默认输入法
