### ISSUE TITLE
"Strictly used for illegal purposes"

### ISSUE THREAD

**Issue by guanzhangrtk** [barry-ran/QtScrcpy#315]
In the file `res/i18n/QtScrcpy_zh.ts`, the Chinese says:

"严禁用于非法用途，否则后果自负"

however the English translation is:

"Strictly used for illegal purposes, or at your own risk"

I think you might want to change it to something like "Strictly forbidden to be used for illegal purposes, or you do so at your own risk".

You might want to consult a lawyer for better wording though :-)

**Comment by NielsMayer** [comment]
i just compiled from latest git source with Qt5.15.2 on Ubuntu. read almost zero documentation, clicked a few buttons and it was running displaying my Android TV on my Desktop! really nice Qt && Android software @barry-ran !

but i did have a good laugh at the message output in the log:

```
This software is completely open source and free. Strictly used for illegal purposes, or at your own risk. You can download it at the following address:

"QtScrcpy  <https://github.com/barry-ran/QtScrcpy>"

adb devices
adb path: /usr/local/src/QtScrcpy/third_party/adb/linux/adb

adb run
AdbProcess::out:List of devices attached
XXXXXXXXXXXXXXXXXXXX	device

start server...
AdbProcess::out:../../../third_party/scrcpy-server: 1 file pushed. 0.1 MB/s (33142 bytes in 0.387s)

AdbProcess::out:[server] INFO: Device: NVIDIA SHIELD Android TV (Android 9)

server start finish in 3.603s

```

**Comment by barry-ran** [comment]
My English is very poor, thanks for reminding（from google translate）

**Comment by neobodiel** [comment]
Hello Barry,
Thanks a lot for your project Qtcrcpy! I have a question (very silly one) : when I install it (on Mac) it all appear in Chinese. Since I unfortunately don’t speak Chinese, I really don’t know how to use it.
Thanks for your feed back!
Cheers
