### ISSUE TITLE
Cannot Display

### ISSUE THREAD

**Issue by wadzib** [barry-ran/QtScrcpy#317]
How to fix this

QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
ERROR: 0:8: '' : No precision specified for (float)
ERROR: 0:9: '' : No precision specified for (float)
ERROR: 0:13: '' : No precision specified for (float)
ERROR: 0:14: '' : No precision specified for (float)
ERROR: 0:15: '' : No precision specified for (float)

**Comment by barry-ran** [comment]
https://github.com/barry-ran/QtScrcpy/blob/33b0d65b19c23de6c8b6e506b076eda253d5241c/config/config.ini#L11
