### ISSUE TITLE
Can't open on MacOS 11 big sur

### ISSUE THREAD

**Issue by yfengtech** [barry-ran/QtScrcpy#318]
Date/Time:        2020-11-23 10:42:00.708 +0800
End time:         2020-11-23 10:43:14.888 +0800
OS Version:       macOS 11.0.1 (Build 20B50)
Architecture:     x86_64h
Report Version:   32

Data Source:      Stackshots
Shared Cache:     1E362DBC-F66C-3135-BCA0-C1BBAE12BC7C slid base address 0x7fff20015000, slide 0x15000

Command:          QtScrcpy
Path:             /Applications/QtScrcpy.app/Contents/MacOS/QtScrcpy
Identifier:       rankun.QtScrcpy
Version:          1.3.3 (1.3.3)
Parent:           launchd [1]
PID:              10982
Time Since Fork:  75s

Event:            hang
Duration:         74.18s
Duration Sampled: 1.10s (process was unresponsive for 73 seconds before sampling)
Steps:            11 (100ms sampling interval)

Hardware model:   MacBookPro16,1
Active cpus:      12
Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 5917s
Time Since Wake:  1543s

Fan speed:        5284 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  11  start + 1 (libdyld.dylib + 87601) [0x7fff2033d631]
  11  main + 2141 (QtScrcpy + 26557) [0x1079997bd]
  11  QCoreApplication::exec() + 130 (QtCore + 2009986) [0x10c9d0b82]
  11  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431 (QtCore + 1989519) [0x10c9cbb8f]
  11  ??? (libqcocoa.dylib + 217107) [0x10ec80013]
  11  -[NSApplication run] + 586 (AppKit + 195546) [0x7fff22c22bda]
  11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366 (AppKit + 251723) [0x7fff22c3074b]
  11  _DPSNextEvent + 883 (AppKit + 257925) [0x7fff22c31f85]
  11  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 199407) [0x7fff28684aef]
  11  ReceiveNextEventCommon + 283 (HIToolbox + 199714) [0x7fff28684c22]
  11  RunCurrentEventLoopInMode + 292 (HIToolbox + 200656) [0x7fff28684fd0]
  11  CFRunLoopRunSpecific + 563 (CoreFoundation + 521918) [0x7fff204186be]
  11  __CFRunLoopRun + 838 (CoreFoundation + 524509) [0x7fff204190dd]
  11  __CFRunLoopDoObservers + 549 (CoreFoundation + 527405) [0x7fff20419c2d]
  11  __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23 (CoreFoundation + 527773) [0x7fff20419d9d]
  11  ___NSRunLoopObserverCreateWithHandler_block_invoke + 41 (AppKit + 9493774) [0x7fff23500d0e]
  11  __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 285 (AppKit + 1849803) [0x7fff22db69cb]
  11  CA::Transaction::commit() + 783 (QuartzCore + 12177) [0x7fff26b9ff91]
  11  CA::Context::commit_transaction(CA::Transaction*, double, double*) + 517 (QuartzCore + 1438579) [0x7fff26cfc373]
  11  CA::Layer::display_if_needed(CA::Transaction*) + 874 (QuartzCore + 153016) [0x7fff26bc25b8]
  8   -[_NSViewBackingLayer display] + 555 (AppKit + 1152888) [0x7fff22d0c778]
  8   -[_NSBackingLayer display] + 475 (AppKit + 1763233) [0x7fff22da17a1]
  8   -[CALayer display] + 183 (QuartzCore + 154890) [0x7fff26bc2d0a]
  8   ??? (libqcocoa.dylib + 157150) [0x10ec715de]
  8   ??? (libqcocoa.dylib + 122892) [0x10ec6900c]
  8   void QWindowSystemInterface::handleExposeEvent<QWindowSystemInterface::SynchronousDelivery>(QWindow*, QRegion const&) + 178 (QtGui + 118898) [0x10c161072]
  7   bool QWindowSystemInterfacePrivate::handleWindowSystemEvent<QWindowSystemInterface::SynchronousDelivery>(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 115 (QtGui + 90339) [0x10c15a0e3]
  7   QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) + 309 (QtGui + 228965) [0x10c17be65]
  7   QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212 (QtCore + 2008436) [0x10c9d0574]
  7   QApplication::notify(QObject*, QEvent*) + 594 (QtWidgets + 72578) [0x10bbb4b82]
  7   QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269 (QtWidgets + 67453) [0x10bbb377d]
  7   ??? (QtWidgets + 436555) [0x10bc0d94b]
  7   ??? (QtWidgets + 447956) [0x10bc105d4]
  7   ??? (QtWidgets + 117650) [0x10bbbfb92]
  7   ??? (QtWidgets + 100590) [0x10bbbb8ee]
  7   QBackingStore::flush(QRegion const&, QWindow*, QPoint const&) + 1207 (QtGui + 1837175) [0x10c304877]
  3   ??? (libqcocoa.dylib + 84333) [0x10ec5f96d]
  1   ??? (libqcocoa.dylib + 85748) [0x10ec5fef4]
  1   -[NSInvocation invoke] + 303 (CoreFoundation + 410624) [0x7fff203fd400]
  1   __invoking___ + 140 (CoreFoundation + 410972) [0x7fff203fd55c]
  1   -[NSWindow _maskRoundedBottomCorners:] + 71 (AppKit + 3876317) [0x7fff22fa55dd]
  1   -[NSView lockFocusIfCanDraw] + 1068 (AppKit + 3148922) [0x7fff22ef3c7a]
  1   CFArrayGetCount + 9 (CoreFoundation + 133866) [0x7fff203b9aea]

**Comment by barry-ran** [comment]
any tips?
