### ISSUE TITLE
荣耀8x手机，在mac软件使用的时候，投影画面拉伸严重，字体变形

### ISSUE THREAD

**Issue by yaochangliang159** [barry-ran/QtScrcpy#32]
<img width="1134" alt="WX20191015-165529@2x" src="https://user-images.githubusercontent.com/13497352/66816529-ce68ec80-ef6c-11e9-9856-f78946782767.png">
如图，投影出来的字体感觉变矮了。。。。整个界面看起来怪怪的

**Comment by barry-ran** [comment]
视频尺寸的问题，1080p宽高比例和你手机的实际宽高比差别太大了，所以会拉伸
分辨率改为native即可
