### ISSUE TITLE
KMT_STEER_WHEEL movement problem for some games.

### ISSUE THREAD

**Issue by Dalkone** [barry-ran/QtScrcpy#325]
Hi!

I've noticed with some games that the KMT_STEER_WHEEL option isn't working correctly. It attempts to click and move up, down, left or right too quickly, sometimes ignoring movement and making moving quite annoying to do. Is there a way to add a delay? Say when you press a key it holds down the movement pad, waits for like 1 or 2ms and then swipe up, down, left or right?

Anyone else having this problem?

**Comment by BobbyWibowo** [comment]
It seems inputs are somehow throttled, or there's a bottleneck somewhere. For simple one click mapping, I notice that I can only submit about 2~3 clicks per second (a far cry from how my phone would 100% register the fastest tap combos I could humanely do to it). So I'm somewhat inclined to wheel emulations' imperfections are related to that too.

**Comment by renanwp2** [comment]
> It seems inputs are somehow throttled, or there's a bottleneck somewhere. For simple one click mapping, I notice that I can only submit about 2~3 clicks per second (a far cry from how my phone would 100% register the fastest tap combos I could humanely do to it). So I'm somewhat inclined to believe that wheel emulations' imperfections are related to that too.
> 
> I also notice that sometimes wheel movement will stop detecting 1 axis if you have moved to that 1 axis for a bit too long. Just like how your cursor will eventually stop after you move to the edge of the screen. Essentially, it's as if the actual cursor doesn't actually get frozen in the center of the emulation screen, making movement detection go off every now and then? I dunno, just a speculation.

The mouse does not keep on center. [dwm](https://dwm.suckless.org/) have some problems on hiding the mouse. When the mouse crosses the boundary, the mouse cursor "teletransports" (LOL I dunno how to explain that) to the opposite side of the screen.

**Comment by barry-ran** [comment]
try v1.7
