### ISSUE TITLE
建议无线连接的默认IP地址可以记住上回连接的地址，或在配置文件中可以配置

### ISSUE THREAD

**Issue by happylenx** [barry-ran/QtScrcpy#328]
因为经常使用本软件的情况下，连接的设备IP很少发生变化，现在每次连接都要输入IP地址，比较麻烦。
如果有这个功能，无线连接会方便很多。
谢谢！

**Comment by mc520666** [comment]
它有这个功能的，你成功连接后点获取设备ip，下一次你只需要点刷新设备列表就可以用了，不需要输入，我也是研究了好几个小时才发现，特意注册了账号来告诉你一下

**Comment by happylenx** [comment]
> 它有这个功能的，你成功连接后点获取设备ip，下一次你只需要点刷新设备列表就可以用了，不需要输入，我也是研究了好几个小时才发现，特意注册了账号来告诉你一下

@mc520666 非常感谢告知！这功能隐藏的挺深啊。

**Comment by LinBoyan** [comment]
感谢告知!
