### ISSUE TITLE
电脑投屏上当前鼠标位置始终有一个小十字

### ISSUE THREAD

**Issue by mwmb2** [barry-ran/QtScrcpy#335]
Ubuntu
QTcreator编译后运行
按已经按下波浪符进行键盘鼠标控制
实际鼠标位置（不是屏幕中央）总有一个小的十字符号。手机屏幕上没有。
用起来很不习惯，怎么去掉呢

**Comment by barry-ran** [comment]
debug版本调试用的，release版本没有
