### ISSUE TITLE
RDP远程桌面或者teamviewer连接远程windows 10电脑打开软件无法正常使用

### ISSUE THREAD

**Issue by YorkOrz** [barry-ran/QtScrcpy#341]
远程机器上配置了可以调用OpenGL及独立显卡资源的
启动服务后显示黑框框窗口点不开
[img](https://i.imgur.com/R5hkFdm.png)

**Comment by barry-ran** [comment]
rdp会限制软件的一些访问opengl的能力，在config.ini里改为软解就可以了
