### ISSUE TITLE
Instructions are not clear

### ISSUE THREAD

**Issue by gaussandhisgun** [barry-ran/QtScrcpy#349]
So, in https://github.com/barry-ran/QtScrcpy#pc-client there are stated that I should just open the project, compile it and run. But my freshly-installed qtcreator states that Project is not set up and that default Desktop profile is used, but it is not suitable. As such, compile button is unavailable. I had no experience with QTCreator before. Ubuntu 18.04

**Comment by gaussandhisgun** [comment]
or, maybe, someone smart enough to actually compile it can send me already built binaries?

**Comment by renanwp2** [comment]
The author's english is not as good as you might think. A native english speaker who knows how to compile and want to help the author can make better instructions for it. I'm not native english speaker and do not know how to properly compile it, but you can read my issue and try my solution (the right one above yours). =) I have "unpatched" one specific patch and I was able tp compile it using my system's Qt. The byproduct of the compilation does not throw any errors, but I am not sure if it is as originally intended.

**Comment by renanwp2** [comment]
Since I have closed my issue: https://github.com/barry-ran/QtScrcpy/issues/348

**Comment by barry-ran** [comment]
This is the foundation, you need to learn qt
