### ISSUE TITLE
[Feature request] Add delay option to KMT_DRAG and KMT_STEER_WHEEL after first click on center

### ISSUE THREAD

**Issue by renanwp2** [barry-ran/QtScrcpy#352]
Some games requires some delay  after clicking the first time on the screen to make the command to work, like [Free Fire](https://apkpure.com/garena-free-fire-android-il/com.dts.freefireth). A delay of 1/30 secs would be enough for sure, but I would ask, if possible, to let the user configure the delay time.

**Comment by renanwp2** [comment]
I know that the delay is necessary because i have tested it with [xbindkeys](https://wiki.archlinux.org/index.php/Xbindkeys) for moving the mouse and clicking on the analog stick.

**Comment by Yamakuzure** [comment]
What delay do you mean exactly?

a. what are you doing exactly (yourself) before the delay shall be happening
b. what will you (or the game) do exactly after that delay?

If I understand this, I can identify the area in the source code where this would have to be added, and can help Barry out on this one.

**Comment by renanwp2** [comment]
> What delay do you mean exactly?
> 
> a. what are you doing exactly (yourself) before the delay shall be happening
> b. what will you (or the game) do exactly after that delay?
> 
> If I understand this, I can identify the area in the source code where this would have to be added, and can help Barry out on this one.

Hi, Yamakuzure. I have been too busy. The delay I want on KMT_STEER_WHEEL works this way: 
1) Before calling the KMT_STEER_WHEEL, click on center of it and, after some time (1/30 seconds should be fine), call KMT_STEER_WHEEL;
2) For KMT_DRAG, its almost the same. Click on center of the start position and then after some time (again 1/30 seconds should be fine) drag to the end position;

**Comment by renanwp2** [comment]
> What delay do you mean exactly?
> 
> a. what are you doing exactly (yourself) before the delay shall be happening
> b. what will you (or the game) do exactly after that delay?
> 
> If I understand this, I can identify the area in the source code where this would have to be added, and can help Barry out on this one.

Hi, Yamakuzure, what a great person you are! Sorry for taking too much time to answer you, I have been too busy (working full time). The delay I want works this way: 

1) Before calling the KMT_STEER_WHEEL, click on center of the analog stick and, after some time (1/30 seconds should be fine), call KMT_STEER_WHEEL as usual. I guess one should take care to not keep clicking on center, since it just clicks on center once a new key (WASD keys) is pressed;
2) For KMT_DRAG, its almost the same. Click on center of the start position,  hold on for some time (again 1/30 seconds should be fine), and then drag the finger to the end position;

If the delay time was adjustable, would be perfect. If not, tell me where to adjust it and I might try to configure it on my way. This delay is based on the FPS of the games (usually 30 FPS).

**Comment by Yamakuzure** [comment]
@renanwp2 : Could you please have a look at this answer in #353 and check whether @Bren1n-SCP means (roughly) the same as you do?
https://github.com/barry-ran/QtScrcpy/issues/353#issuecomment-776756379

Both sound quite identical for me, but if there _is_ a difference, I'd like to know about it before I meddle with the code. :wink:

**Comment by renanwp2** [comment]
> @renanwp2 : Could you please have a look at this answer in #353 and check whether @Bren1n-SCP means (roughly) the same as you do?
> [#353 (comment)](https://github.com/barry-ran/QtScrcpy/issues/353#issuecomment-776756379)
> 
> Both sound quite identical for me, but if there _is_ a difference, I'd like to know about it before I meddle with the code. wink

Hi, again,  Yamakuzure!

Yes, it looks the same issue as mine !

**Comment by renanwp2** [comment]
> @renanwp2 : Could you please have a look at this answer in #353 and check whether @Bren1n-SCP means (roughly) the same as you do?
> [#353 (comment)](https://github.com/barry-ran/QtScrcpy/issues/353#issuecomment-776756379)
> 
> Both sound quite identical for me, but if there _is_ a difference, I'd like to know about it before I meddle with the code. wink

Ah, do not consider a key as new, if another one (among WASD keys) is already pressed. For example, if you are pressing W and then press D without releasing W , do not consider the D key as a new key pressed. I am not sure, but that might cause problems due to the excessive amount of clicking on center.

**Comment by lonerwolf** [comment]
同样遇到这个问题，使命召唤会突然卡住，试过TCGAMES也一样

**Comment by barry-ran** [comment]
[v1.7.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.7.0) Added delay function, you can try it

**Comment by renanwp2** [comment]
Tested. Looks fine,
