### ISSUE TITLE
Workflow files not in order; All checks fail during Qt Install phase.

### ISSUE THREAD

**Issue by Yamakuzure** [barry-ran/QtScrcpy#355]
My pull request #354 fails all tests, because there is an error in your workflow files.

I think the relevant issues start here: (During "Install Qt")
https://github.com/barry-ran/QtScrcpy/pull/354/checks?check_run_id=1844939436#step:3:333

Unfortunately I am too new with "GitHub Actions" to be of real help. I just have started on one of my projects, as I used to utilize travis-ci.org.

**Comment by barry-ran** [comment]
Fixed
