### ISSUE TITLE
how to use local adb?

### ISSUE THREAD

**Issue by jdf159357** [barry-ran/QtScrcpy#358]
when use QtScrcpy owns adb, and cmd error adb server is out of date.  killing...

**Comment by Yamakuzure** [comment]
In the directory where Qtscrcpy is located, I put a symlink to `/data/Android/SDK/platform-tools/adb` (That's my local Android SDK as you might already have guessed.)

So basically you can just copy platform-tools/adb (or platform-tools\adb.exe on Windows?) into the same directory as Qtscrcpy and it should be used.

**Comment by jdf159357** [comment]
> In the directory where Qtscrcpy is located, I put a symlink to `/data/Android/SDK/platform-tools/adb` (That's my local Android SDK as you might already have guessed.)
> 
> So basically you can just copy platform-tools/adb (or platform-tools\adb.exe on Windows?) into the same directory as Qtscrcpy and it should be used.

Thanks, it works

**Comment by barry-ran** [comment]
[config.ini](https://github.com/barry-ran/QtScrcpy/blob/33b0d65b19c23de6c8b6e506b076eda253d5241c/config/config.ini#L17) is a better choice

**Comment by Oaklight** [comment]
> [config.ini](https://github.com/barry-ran/QtScrcpy/blob/33b0d65b19c23de6c8b6e506b076eda253d5241c/config/config.ini#L17) is a better choice

where is it in linux?
