### ISSUE TITLE
Fix Original resolution setting

### ISSUE THREAD

**Issue by Racansky** [barry-ran/QtScrcpy#362]
When I use the classic Scrcpy, the image on the monitor will start in the correct resolution of the phone - 1560x720.
When I use QtScrcpy, no matter how I set it up, the mirrored screen is simply reduced. Although I try the keyboard shortcut "Resize window to 1: 1 Ctrl + g".
I'm still testing ... when I enter my resolution directly into config \ userdata.ini .. unfortunately QtScrcpy will overwrite it after startup. This is probably because the PC monitor has fewer pixels (1200px) in height than the phone (1560px), which automatically reduces it.
Unfortunately, when the phone's display is turned to landscape, there is no way to achieve a 1: 1 resolution back.

**Comment by barry-ran** [comment]
What does  simply reduced mean？
