### ISSUE TITLE
增加文件传输进度和保存路径的提示

### ISSUE THREAD

**Issue by LinBoyan** [barry-ran/QtScrcpy#363]
软件支持向安卓设备推送文件。
但是传输的创建、结束、当下状态没有通过命令行窗口或手机端展示，需要通过网络流量判断。
如果需要更改推送到安卓设备的文件保存路径，则需要进入软件的配置文件修改，很不方便。
建议在后续版本中为文件传输功能增设栏目，即使只是命令行窗口中的一句"transmission done"。

**Comment by barry-ran** [comment]
有啊
![image](https://user-images.githubusercontent.com/18702692/110230845-bec9b980-7f4e-11eb-9891-2384ca0ea762.png)
