### ISSUE TITLE
Linux amd-64 version can download here

### ISSUE THREAD

**Issue by Hemingway2003** [barry-ran/QtScrcpy#365]
[QtScrcpy.zip](https://github.com/barry-ran/QtScrcpy/files/6074536/QtScrcpy.zip)
Please try to unzip this and input:
$ chmod +x QtScrcpy
$ ./QtScrcpy

**Comment by barry-ran** [comment]
Can you integrate the packaging script into QtScrcpy？[publish_for_ubuntu.sh.todo](https://github.com/barry-ran/QtScrcpy/blob/master/ci/linux/publish_for_ubuntu.sh.todo)
