### ISSUE TITLE
Need help, how can I make swipes faster

### ISSUE THREAD

**Issue by lukistar** [barry-ran/QtScrcpy#375]
Hello there!

I have been playing a game where everything is done by swiping the screen. Whenever I used scrcpy my swipes were much slower than using my finger on the actual screen(around 30 % slower). But now I found this nice library and it seems that here it would be easier to change the way swipes works.

So I was wondering is it possible to use "right click" of the mouse to trigger fast swipe? The starting position of the swipe would be hard-coded point and the end position would be the right click.

Is this possible without changing the code, or do I have to rewrite something myself, if you could give me a hint where to start that would be wonderful.

**Comment by barry-ran** [comment]
You need to change some code, look [this](https://github.com/barry-ran/QtScrcpy/blob/33b0d65b19c23de6c8b6e506b076eda253d5241c/QtScrcpy/device/controller/inputconvert/inputconvertgame.cpp#L116)
