### ISSUE TITLE
Very high latency

### ISSUE THREAD

**Issue by pubguser** [barry-ran/QtScrcpy#377]
As you can see from this picture my latency is very high almost 140ms at 1080p. How can I reduce it

![Screenshot_20210323-014949_Brave](https://user-images.githubusercontent.com/81191186/112053255-20f30300-8b7a-11eb-96ee-5b8ad26ffd39.png)

**Comment by barry-ran** [comment]
140ms is very high latency? Try to reduce the bit rate
