### ISSUE TITLE
使用安兔兔软件测试多点触控，对比scrcpy的延迟比较明显，对比感觉是数据接收对比比较耗时

### ISSUE THREAD

**Issue by yaojianzhong** [barry-ran/QtScrcpy#38]
1、手机上安装安兔兔测试软件，使用多点触控测试
2、鼠标点击窗口，发现手机上先显示点击的红圈，然后投屏窗口上后显示，对比scrcpy显示是同步的
3、从手机上很快显示点击效果来看说明点击事件传送是ok的，那就是从接受画面数据到渲染的过程不如scrcpy，对比代码看怀疑是接收视频数据的方式qt的信号槽不如c的直接调用

**Comment by barry-ran** [comment]
最新版本已经同步scrcpy，延时有所减少
