### ISSUE TITLE
反馈一个bug 

### ISSUE THREAD

**Issue by nosiyBUGS** [barry-ran/QtScrcpy#387]
进入远程桌面启动这个软件会黑屏 不显示。但把软件打开后再进远程桌面操作手机窗口能正常显示

**Comment by barry-ran** [comment]
试试[FAQ](https://github.com/barry-ran/QtScrcpy/blob/master/docs/FAQ.md#%E5%8F%AF%E4%BB%A5%E6%8E%A7%E5%88%B6%E4%BD%86%E6%97%A0%E6%B3%95%E7%9C%8B%E5%88%B0%E7%94%BB%E9%9D%A2)
