### ISSUE TITLE
希望增加或替换成ESC为返回、记住点X最小化或退出，鞠躬

### ISSUE THREAD

**Issue by lonznt** [barry-ran/QtScrcpy#393]
不知道是不是也有同学和我一样，习惯并也感觉esc才是顺手的返回键。
当前版本点x每次都会蹦出退出or最小化警告，希望增加设置一劳永逸。
谢谢开发者呀，辛苦了辛苦了。

**Comment by barry-ran** [comment]
[v1.7.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.7.0)
