### ISSUE TITLE
readyReadStandardOutput和readyReadStandardError信号消息截断的问题

### ISSUE THREAD

**Issue by mo2phone** [barry-ran/QtScrcpy#4]
AdbProcess类的代码   

 connect(this, &QProcess::readyReadStandardOutput, this,
            [this](){
        m_standardOutput =m_standardOutput+ QString::fromLocal8Bit(readAllStandardOutput());
        qInfo(QString("AdbProcess::out:%1").arg(m_standardOutput).toUtf8());
    });

标准输出和错误输出都有这问题；

**Comment by barry-ran** [comment]
- 调试发现了有时候可以获取ip地址，有时候获取不到很奇怪，debug一看才发现的，因为信息分次返回，如果刚好最后一次被切断的数据没有ip地址信息，这样就死都获取不到ip地址；
- 获取ip地址的方式不严谨，adb -s *** shell ifconfig 这才是获取ip地址严谨的方式，你哪个命令只能获取wifi下的ip地址，如果手机开热点给电脑，这个就无法获取了，而手机真实的ip地址是通过rmnet_data字段获取的。

**Comment by barry-ran** [comment]
[fixed](https://github.com/barry-ran/QtScrcpy/commit/ad655f071aabb28808deeee6c9134ba08ca4272c)
