### ISSUE TITLE
新版本建议界面字体大一点，然后窗口支持拖动缩放

### ISSUE THREAD

**Issue by ustbmeng** [barry-ran/QtScrcpy#412]
比如现在的主界面，精简模式下，上方的别名列表，和下方的ID列表，是均分的，不能拖动。整个主窗口边框也不能拖动。
实际上下方的ID列表，平时并不需要过分关注。它占用的面积有些太大了。
上方的别名列表建议占的空间多些，字体大些。
谢谢谢谢谢谢。
为了将字体变大点，我都将显示器分辨率从1920*1080，改到了1366*768，实在没办法。在1080界面下，字体小的能看瞎。：（

**Comment by barry-ran** [comment]
试试精简模式
