### ISSUE TITLE
小米无法和平精英不能映射？

### ISSUE THREAD

**Issue by singrela** [barry-ran/QtScrcpy#42]

**Comment by singrela** [comment]
按~后没有反应

**Comment by barry-ran** [comment]
可以正常控制吗？

**Comment by singrela** [comment]
就是打开和平精英以后，按~键，只有鼠标消失了，没有其他任何反应，然后按键盘除了~键其他所有键没有反应。按了~键以后鼠标又恢复了，手机小米8，官方MIUI10开发版9.8.1，已勾选自定义映射且用的默认脚本，usb链接，投屏正常。还有投屏以后电脑上手机框框旁边那几个功能键，音量加，音量减那几个，我的只有下拉状态栏和息屏有效，其他音量加减，home键，返回什么的均无效，可能用的是全面屏手势的原因？

**Comment by singrela** [comment]
是    除了~键其他所有键没有反应，按了~键以后鼠标又恢复了

**Comment by singrela** [comment]
是 然后按键盘除了破折号键以外的其他所有键没有反应。按了破折号键以后鼠标又恢复了，

**Comment by barry-ran** [comment]
参照FAQ文档，开发者选项里打开允许模拟控制

**Comment by singrela** [comment]
一些按键按了没有效果，有空格，z，x，c，tab，r键，按shift键变成了开枪。录了个视频 https://pan.baidu.com/s/1uoAJc5dgy2mE4V73BO7U_g

**Comment by barry-ran** [comment]
键位重置为默认，可以对比readme里默认映射位置是否对应

**Comment by singrela** [comment]
![image](https://user-images.githubusercontent.com/48936071/67734618-789c4600-fa3c-11e9-8582-9eed180322ac.png)
脚本是不是写错了呀，shift只有车加速的功能啊，所以在人物拿枪行走的情况下，车加速那个按键正好在开枪的那边，按shift键就开枪了。

**Comment by barry-ran** [comment]
设计如此，shift只有车加速的功能，可以根据自己的需要修改脚本，这只是我的习惯而已

**Comment by singrela** [comment]
好，感谢
