### ISSUE TITLE
功能建议 - 增加最小化投屏到系统托盘以及记住设定的功能

### ISSUE THREAD

**Issue by netsonicyxf** [barry-ran/QtScrcpy#422]
1. 现在程序主界面可以最小化到系统托盘，但投屏只能最小化到任务栏，能否也加个选项：最小化到系统托盘
2. 每次启动程序主界面，都要选一些**固定**的选项，但下次启动就没了，还要重新再选一遍。能否生成不同选项的配置文件，并且可以在启动快捷方式加载配置文件，就不用每次重新选择选项了。

**Comment by barry-ran** [comment]
[v1.7.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.7.0)
