### ISSUE TITLE
Add "don't ask again" option for close button

### ISSUE THREAD

**Issue by Huhni** [barry-ran/QtScrcpy#428]
When closing QtScrcpy this dialog shows up:
![image](https://user-images.githubusercontent.com/33904029/122749374-8cd62c00-d28d-11eb-8fef-8c7ff6cb6871.png)

Please add a checkbox to remember the last used option, so that it closes immediately when clicking the close button. 
Currently it even blocks Windows from shutting down, when the program is still running.

**Comment by barry-ran** [comment]
ok

**Comment by barry-ran** [comment]
[v1.7.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.7.0)
