### ISSUE TITLE
How to get correct Phone size?

### ISSUE THREAD

**Issue by fluffyloopy** [barry-ran/QtScrcpy#43]
is there any way to fix screen resolution? my phone looks as if its been squashed since the app shows the phone to be shorter and wider than my phone's actual res which is 1080 x 2340 pixels, 19.5:9 ratio

**Comment by fluffyloopy** [comment]
How?

**Comment by barry-ran** [comment]
![TIM图片20191028214929](https://user-images.githubusercontent.com/18702692/67683714-d1cc9100-f9cc-11e9-9952-c7f370aa72a0.png)

**Comment by fluffyloopy** [comment]
oh, thanks.
