### ISSUE TITLE
Keymappings keep on stopping

### ISSUE THREAD

**Issue by crimvirt** [barry-ran/QtScrcpy#433]
Whenever I play PUBG, there were times that keymappings just suddenly don't work and I have to reset QTscrcpy by clicking on "USB Connect" again in order for it to work again. So it's almost unplayable if this keeps on occuring. It occurs every few minutes, I don't know what causes it. Am I pressing on keyboard that causes it to occur? Whenever this happens, my steer wheel for movement is stuck so I have to tap on the phone to make it stop.

**Comment by barry-ran** [comment]
try [v1.7.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.7.0)

**Comment by crimvirt** [comment]
There were still times that it stops. But not often as the 1.6.0

**Comment by crimvirt** [comment]
> try [v1.7.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.7.0) 

Also before it stops working, the steerwheel"WASD" will become camera look first. The button A and D will become horizontal camera look control and W and S for vertical.
