### ISSUE TITLE
USB debugging stops working

### ISSUE THREAD

**Issue by crimvirt** [barry-ran/QtScrcpy#434]
This occurs every couple of minutes, when this happens, the screencast freezes, so I have to unplug and plug the usb again to make it work. What causes it to occur?

**Comment by guanzhangrtk** [comment]
Have you checked adb logs for errors?

**Comment by crimvirt** [comment]
Nothing is showing up in the logs.

**Comment by guanzhangrtk** [comment]
Talking about the `adb` logs, not the log from Qtscrcpy window.

**Comment by crimvirt** [comment]
> Talking about the `adb` logs, not the log from Qtscrcpy window.

Where can I find adb logs, there's no CMD shown

**Comment by guanzhangrtk** [comment]
I don't know what OS you're on, but on macOS, the `adb` binary is in `/Applications/QtScrcpy.app/Contents/MacOS/adb`. On Windows it's likely somewhere in `C:\Program Files\Qtscrcpy` or something like that. If you can't find it you can always download the official `adb` binary from Google. Once you have the binary you can just run `adb logcat` from the command prompt and watch for relevant messages when it stops working. Another thing you can try is download and use the original `scrcpy` and see if you encounter the same issue.

**Comment by crimvirt** [comment]
> I don't know what OS you're on, but on macOS, the `adb` binary is in `/Applications/QtScrcpy.app/Contents/MacOS/adb`. On Windows it's likely somewhere in `C:\Program Files\Qtscrcpy` or something like that. If you can't find it you can always download the official `adb` binary from Google. Once you have the binary you can just run `adb logcat` from the command prompt and watch for relevant messages when it stops working. Another thing you can try is download and use the original `scrcpy` and see if you encounter the same issue.

In scrcpy, I don't encounter this issue. QtScrcpy have been stopping constantly lately.

**Comment by guanzhangrtk** [comment]
In that case that's probably something that barry will have to look into. But without any logs there isn't much anybody can do.

**Comment by crimvirt** [comment]
Can I run QtScrcpy on command prompt?
