### ISSUE TITLE
Cool app but

### ISSUE THREAD

**Issue by GamesDii-ttv** [barry-ran/QtScrcpy#437]
Like title says.. cool app but my app kinda always lag when I want to stream.. delays the video output.. any solution??

**Comment by barry-ran** [comment]
Try to reduce resolution and bit rate

**Comment by GamesDii-ttv** [comment]
> Try to reduce resolution and bit rate

It's on lowest possible..

**Comment by dijo7** [comment]
if you have display port type c, then try usb 3.1 gen 2 type c to c cable. 

Optimization:
 Right Click qtscrcpy.exe, and go to Properties. Click on Compatibility. set disable full screen optimization,
- Click on the Change High DPI Setting button (the button is new with the 1803 update).
At the bottom, tic the box next to 'Override High DPI Scaling Behaviour' .

Setting a 0.5 msec timer resolution:
You can get/set the timer resolution by using this small app.
https://vvvv.org/contribution/windows-system-timer-tool
(only minimize the app)

**Comment by dijo7** [comment]
if you have display port type c, then try usb 3.1 gen 2 type c to c cable. 

Optimization on Windows:
 Right Click qtscrcpy.exe, and go to Properties. Click on Compatibility. 
- set disable full screen optimization,
- Click on the Change High DPI Setting button (the button is new with the 1803 update).
At the bottom, tic the box next to 'Override High DPI Scaling Behaviour' .

**Comment by dijo7** [comment]
if you have display port type c, then try usb 3.1 gen 2 or higher type c to c cable.

Optimization on Windows:
Right Click qtscrcpy.exe, and go to Properties. Click on Compatibility.

set disable full screen optimization,
Click on the Change High DPI Setting button (the button is new with the 1803 update).
At the bottom, tic the box next to 'Override High DPI Scaling Behaviour' .

**Comment by dijo7** [comment]
if you have display port type c, then try usb 3.1 gen 2 or higher type c to c cable.

Optimization on Windows:
Right Click qtscrcpy.exe, and go to Properties. Click on Compatibility
set disable full screen optimization.
Click on the Change High DPI Setting button (the button is new with the 1803 update).
At the bottom, tic the box next to 'Override High DPI Scaling Behaviour' .

**Comment by GamesDii-ttv** [comment]
> if you have display port type c, then try usb 3.1 gen 2 or higher type c to c cable.
> 
> Optimization on Windows:
> Right Click qtscrcpy.exe, and go to Properties. Click on Compatibility
> set disable full screen optimization.
> Click on the Change High DPI Setting button (the button is new with the 1803 update).
> At the bottom, tic the box next to 'Override High DPI Scaling Behaviour' .

Works for you mate?

**Comment by dijo7** [comment]
Definitely. 

You could check out this if its pc problem:
https://youtu.be/wos5o2sUNbk

**Comment by dijo7** [comment]
Definitely.

Do Try PrimoCache, make your computer more responsive for streaming, gaming and producing, notable difference in latency
https://www.romexsoftware.com/en-us/primo-cache/

You could check out this if its pc problem:
https://youtu.be/wos5o2sUNbk

**Comment by GamesDii-ttv** [comment]
The settings doesn't work.. still lag.. i need better option.. any way around to make it without capture card

**Comment by GamesDii-ttv** [comment]
Now I have problem that mic doesn't work in-game but worked in past.. any solution
