### ISSUE TITLE
中文输入是否可以支持呢？

### ISSUE THREAD

**Issue by yqlicglingfei** [barry-ran/QtScrcpy#45]
无法中文输入，这一点确实有些可惜，要是加上这个的话，体验会好很多。

**Comment by wuyusite** [comment]
是呀，不能用键盘直接输入中文这点稍稍有些可惜了

**Comment by barry-ran** [comment]
安装搜狗或者qq输入法都是可以的

**Comment by 7starzz** [comment]
> 安装搜狗或者qq输入法都是可以的

实测在win10英文版加装中文包的情况下，装了搜狗输入法，还是无法通过PC在手机上录入中文
