### ISSUE TITLE
Answer

### ISSUE THREAD

**Issue by GamesDii-ttv** [barry-ran/QtScrcpy#454]
Do i need strong pc for qtscrpy.. cuz my sh&t is lagging

**Comment by dijo7** [comment]
Ofcourse not!  Run qtscrpy both on a potato and high end pc, you get same difference. Your PC just acts as a monitor. What matters is the data transfer speed, mobile device performance, UFS technology, PC storage device type and the USB cable type.

**Comment by GamesDii-ttv** [comment]
> Ofcourse not! Run qtscrpy both on a potato and high end pc, you get same difference. Your PC just acts as a monitor. What matters is the data transfer speed, mobile device performance, UFS technology, PC storage device type and the USB cable type.

Thanks man.. just wondering why my thing still lagging even on lowest bitrate possible
