### ISSUE TITLE
获取ip地址不严谨

### ISSUE THREAD

**Issue by mo2phone** [barry-ran/QtScrcpy#5]
现在的方法只能获取手机和电脑都通过wifi连接下，实际上是无法获取到用户手机的真实IP地址的，

另外一种情况是手机开热点，电脑连接，这时候手机和电脑也在同一个局域网；

adb -s **** shell ifconfig

可以考虑通过，获取wlan swlan rmnet_data下的ip地址；
wlan对于手机和电脑普通wifi连接；
swlan，手机开热点给电脑连接；
rmnet_data手机的真实ip地址；

也不可以不用考虑的这么细致，这个只是个人看法；

**Comment by barry-ran** [comment]
[fixed](https://github.com/barry-ran/QtScrcpy/commit/ad655f071aabb28808deeee6c9134ba08ca4272c)
