### ISSUE TITLE
关于和平精英脚本

### ISSUE THREAD

**Issue by sbsfg** [barry-ran/QtScrcpy#50]
很高兴大佬弄了和平精英按键脚本映射支持，我和朋友试玩了几局，发现有一点小bug,就是小眼睛按键能用但是视角转不动，我不会编程搜了好多看了好多关于脚本的修改，自己弄了好多天还是搞不定，就连某个按键想要换成左下角的Ctrl都不会了。。。。我太难了，希望大佬更新一下脚本呗~~感激不尽

**Comment by barry-ran** [comment]
小眼睛功能没有实现，按键更换可以参考脚本文档
