### ISSUE TITLE
Unable to activate key-mapping

### ISSUE THREAD

**Issue by BeardJesus** [barry-ran/QtScrcpy#500]
### My issue :

I'm not able to control the game as intended using the keys set in the .json file I applied. 
Pressing 	the "old-switchKey": "Key_Backspace" or the "switchKey": "RightButton" doesn't seem to have any effect -> I'm still not able to go forward using the "W" key on my keyboard

### Status :

- I'm using the 1.7.1 windows build
- Windows 10
- French keyboard (not sure it matters because I can switch to qwerty using shift + alt)
- Here are the options i'm using :

![image](https://user-images.githubusercontent.com/16869232/134657577-4d56ed95-b077-45c8-861c-cb1db624a20e.png)

And I enabled the .json like so :

![image](https://user-images.githubusercontent.com/16869232/134659966-f099fd2e-0adf-4945-9e98-d1a897af4912.png)

The .json file i'm using is a .json I grabbed from the issue #413

### What I tried

1. Pressing the `²` key (which is apparently the `~` key for english keyboard) :
![image](https://user-images.githubusercontent.com/16869232/134659000-14f1d77f-d5d5-4a86-bae7-0193496f43d3.png)
2. Pressing the `~` key like a french : (leaving altGR pressed and then press the ~ key)
![image](https://user-images.githubusercontent.com/16869232/134659082-c3b99d3d-4d80-43e7-a3b5-5f27baec99ab.png)
3. Pressing the right click on my mouse while the focus was on my phone screen (according to .json which mentions `"switchKey": "RightButton"`) : that ended up in a game popup asking me if i want to leave the game
4. I also tried changing the `"switchKey": "RightButton"` to `"switchKey": "Key_P" `

Of course, after each of these tests I tried to move forward in-game by pressing "W" (in french and english keyboard layout just in case) to no avail

No message appeared in the console when I tried to switch "keymap modes", I'm not sure if there should be any ¯\\_(ツ)_/¯

A cool way to bypass this issue would be to add a button to the GUI to force the keymap switch :)
Until then, I can't use the keymap feature ^^'

Thank you in advance for your attention and for your work !
非常感谢！

**Comment by BeardJesus** [comment]
I restarted my computer and I now can enable the custom mode... (with a message displayed in the console)

nothing to see here folks ._.

I thought it may have been because I do have a lot of softwares that certain shortcut (even though it is more complicated than just "press the ~ key"

My bad then, I'm closing this issue :)

**Comment by naxwh** [comment]
Where can i get Genshin keymap

**Comment by BeardJesus** [comment]
> Where can i get Genshin keymap

I literally gave the answer in my post, please read the issue mentioned below my 2nd screenshot

**Comment by naxwh** [comment]
oh sry I forgot to delete this comment

**Comment by rp-web** [comment]
I'm facing this same problem but I didn't have the same luck as Radwolf. I'm using Archcraft, kernel 6.0.5-zen1-1-zen, pt-br and us keyboard (alt + shift to shift).

I was getting and error when I tried to apply the script, It worked opening it with sudo on the terminal, now the message "Script updated, current keymap mode:normal, Press ~ key to switch keymap mode" appears on the console but the only key that works is esc, middle, left and right mouse buttons :(

**Comment by imRadwolf** [comment]
Maybe there's a real bug under Linux so I think it would be wise to open a new issue to get some help, as this one is closed. Feel free to link this one in your new issue if need be !

**Comment by rp-web** [comment]
Thanks I'll open a new one almost identical as yours, I was looking in the json file and I was thinking if I can change the switchKey to another than "~" to see if works, the first try I got an error so I'm looking for other keymaps to see if there's anything different to try and see if works before opening the issue. Thanks for the fast reply.

**Comment by rp-web** [comment]
I don't know why but now is working :/ I just added "old-switchKey": "Key_QuoteLeft", that I saw on some old keymaps but I don't know if this was the fix, I think it was a bug like you said, sorry to bother your brother.
