### ISSUE TITLE
关于适配屏幕

### ISSUE THREAD

**Issue by chenxu-Git** [barry-ran/QtScrcpy#51]
Hi~ 大佬你好鸭，有一些异形屏手机投屏之后，尺寸会被挤压，希望能更新拉伸~ 谢谢大佬_(:з」∠)_

**Comment by yxtj** [comment]
试试分辨率选择native。对非16:9的矩形屏幕都没有问题。

**Comment by chenxu-Git** [comment]
好的~谢谢！
