### ISSUE TITLE
无线功能很不稳定

### ISSUE THREAD

**Issue by cool-delete** [barry-ran/QtScrcpy#53]
Android:9
rom:funtouchOS_9
打开了usb调试模式
7月第一次安装是可以无线的 后来就一直不行了
按教程走到启动adbd后 
点击无线连接会等待1min 然后返回链接失败 可是重复点击就显示已经链接了 哪怕是点击无线断开后点击无线连接 仍然显示已经链接 然后刷新列表
`update devices...
adb run
AdbProcess::out:List of devices attached

AdbProcess::error:* daemon not running; starting now at tcp:5037
* daemon started successfully

update devices...
adb run
AdbProcess::out:List of devices attached
9bbd2b54	device

get ip...
adb run
AdbProcess::out:wlan0     Link encap:UNSPEC    Driver icnss
          inet addr:192.168.8.100  Bcast:192.168.8.255  Mask:255.255.255.0 
          inet6 addr: fe80::9663:72ff:fe8c:d09f/64 Scope: Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4541 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:5580 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:3000 
          RX bytes:3178241 TX bytes:791819

start devices adbd...
adb run
AdbProcess::out:restarting in TCP mode port: 5555

wireless connect...
adb run
AdbProcess::out:failed to connect to 192.168.8.100:5555

wireless connect...
adb run
AdbProcess::out:already connected to 192.168.8.100:5555

wireless disconnect...
adb run
AdbProcess::out:disconnected 192.168.8.100

update devices...
adb run
AdbProcess::out:List of devices attached
9bbd2b54	device
192.168.8.100:5555	offline

wireless connect...
adb run
wait for the end of the current command to run

AdbProcess::out:failed to connect to 192.168.8.100:5555

wireless connect...
adb run
AdbProcess::out:already connected to 192.168.8.100:5555

update devices...
adb run
AdbProcess::out:List of devices attached
9bbd2b54	device
192.168.8.100:5555	offline
`

**Comment by barry-ran** [comment]
安卓设备和电脑是在同一个局域网吗
