### ISSUE TITLE
全屏上面的那个图标是做什么的？

### ISSUE THREAD

**Issue by iforlost** [barry-ran/QtScrcpy#534]
![image](https://user-images.githubusercontent.com/95844542/145363795-3734d146-76e8-44a1-92c7-af9be9bdfaf4.png)

**Comment by iforlost** [comment]
另外的问题：有保持屏幕长亮的选项吗？，如何快速点亮屏幕？

**Comment by vladimire-chen** [comment]
> 另外的问题：有保持屏幕长亮的选项吗？，如何快速点亮屏幕？

上面那个是群控,长亮的话,不知道保持唤醒行不行

**Comment by zieglar** [comment]
保持唤醒是常亮，快速点亮屏幕是右键双击
