### ISSUE TITLE
自定义视频尺寸为480p, 720p, 1080p 以及全屏显示的时候, 对于全面屏手机, 横纵比例会失调

### ISSUE THREAD

**Issue by JackalZhao** [barry-ran/QtScrcpy#55]
自定义视频尺寸为480p, 720p, 1080p 以及全屏显示的时候, 对于全面屏手机, 横纵比例会失调
如下图1所示为自适应尺寸: 
![图1](https://user-images.githubusercontent.com/19181833/69715407-26d20300-1143-11ea-9b57-2644eadb6214.png)

如下图2为启动分辨率为720p的时候, 出现了横纵比例失调: 
![图片](https://user-images.githubusercontent.com/19181833/69715506-53861a80-1143-11ea-81b5-a351f823861c.png)

如下图为竖屏全屏的时候, 只是填充屏幕了: 
![图片](https://user-images.githubusercontent.com/19181833/69715600-86301300-1143-11ea-81e6-7b86161bad4b.png)

建议自定义视频尺寸的时候可以先获取屏幕分辨率, 得到x, y的比例, 保持原屏幕的比例; 也建议全屏填充的时候能保持投屏比例.

**Comment by barry-ran** [comment]
#96
