### ISSUE TITLE
最新的1.8.0 mac安装下来之后，不能通过安全验证，之前的版本是可以的

### ISSUE THREAD

**Issue by nangonghan** [barry-ran/QtScrcpy#551]

**Comment by Maddaxman** [comment]
在安全和隐私那里，仍然运行

**Comment by JingleDingDang** [comment]
sudo xattr -rd com.apple.quarantine /Applications/QtScrcpy.app

终端内用这个命令关闭签名校验，需要输入当前用户密码

**Comment by nangonghan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
