### ISSUE TITLE
鸿蒙2.0连接闪退

### ISSUE THREAD

**Issue by IloveTTLHz** [barry-ran/QtScrcpy#568]
已开启USB调试模式，连接约0.5秒后闪退
update devices...
adb run
AdbProcess::error:* daemon not running; starting now at tcp:5037

start server...
AdbProcess::error:* daemon started successfully

AdbProcess::out:List of devices attached
U9U6R20521002421	device

AdbProcess::out:/Volumes/QtScrcpy/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed, 0 skipped. 38.2 MB/s (40067 bytes in 0.001s)

AdbProcess::out:27183

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

AdbProcess::out:[server] INFO: Device: HUAWEI MRX-W19 (Android 10)

AdbProcess::out:

server start finish in 0.388s

**Comment by IloveTTLHz** [comment]
update devices...
adb run
AdbProcess::error:* daemon not running; starting now at tcp:5037

AdbProcess::error:* daemon started successfully

AdbProcess::out:List of devices attached
U9U6R20521002421	device

start server...
AdbProcess::out:/Volumes/QtScrcpy/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed, 0 skipped. 76.0 MB/s (40067 bytes in 0.001s)

AdbProcess::out:27183

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

AdbProcess::out:[server] INFO: Device: HUAWEI MRX-W19 (Android 10)

AdbProcess::out:

server start finish in 0.464s

**Comment by IloveTTLHz** [comment]
我知道解决方法了，只要同时连接华为鸿蒙的开发工具DevEco-Studio随便怎么折腾也不会闪退，请问大大有兴趣加入对鸿蒙设备的欺骗功能吗？

**Comment by IloveTTLHz** [comment]
我知道解决方法了，只要同时连接华为鸿蒙的开发工具DevEco-Studio随便怎么折腾也不会闪退，请问大大有兴趣加入对鸿蒙设备的欺骗功能吗？

**Comment by chanchaw** [comment]
你的问题解决了么。我也鸿蒙2.0，通过USB连接到电脑后在“USB线” -> “刷新列表” 后，没有发现任何设备。在开与不开“华为手机助手”的情况下都是这样。请问是我的操作哪里不对么？
