### ISSUE TITLE
输入法无法输入中文

### ISSUE THREAD

**Issue by jgck-HUI** [barry-ran/QtScrcpy#582]
之前好像能输入中文，我好像换了输入法就不能输入中文了，目前支持那个输入法输入中文？？？

**Comment by cssnote** [comment]
搜狗支持挺完美。

**Comment by TangYuanHuan** [comment]
> 搜狗支持挺完美。

请问你的是win还是linux系统，我的ubuntu20不能输入中文，不知道要怎么设置

**Comment by jgck-HUI** [comment]
可以用 讯飞输入法



| |
z3515235474
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月20日 22:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [barry-ran/QtScrcpy] 输入法无法输入中文 (Issue #582) |

搜狗支持挺完美。

请问你的是win还是linux系统，我的ubuntu20不能输入中文，不知道要怎么设置

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shiyunjie45** [comment]
问题一直都在,但是一直不解决......

**Comment by yqlicglingfei** [comment]
华为手机自带百度输入法确实不支持。

**Comment by amadisme** [comment]
now. Any input way doesn't work. Drive me crazy

**Comment by caoyirui** [comment]
> 华为手机自带百度输入法确实不支持。

Windows电脑用的搜狗输入法的话，华为手机上面也安装个搜狗输入法就能支持吗？还是也不行？

**Comment by firstuanl** [comment]
> 华为手机自带百度输入法确实不支持。

用这个只进英文，之前用小狼毫倒是可以
