### ISSUE TITLE
投屏协议问题 投屏延迟问题

### ISSUE THREAD

**Issue by m986883511** [barry-ran/QtScrcpy#588]
如果只用adb获取手机画面，应该很难达到60ms延迟吧，我看您csdn上写的是300ms以内，这种fps游戏基本玩不了。

据我所知投屏协议还有airplay和其他的，不知道作者是否了解都完投屏，斗鱼直播这种软件所使用的投屏协议。他们的延迟真的很低，都玩能在60ms以内。

如果使用投屏协议也能支持苹果了。

期待答复。

**Comment by barry-ran** [comment]
1. 可以玩fps游戏的，最高可以达到90fps，这个你可以实际测试一下
2. airplay等其他投屏协议和目前方案没法比，你可以实际对比下两者延时

**Comment by m986883511** [comment]
我实际完了一下和平，画面太糊了，和手机配置有关系吗，我的时麒麟的810处理器，延迟倒不是很大。

你说airplay和目前的没法比，能详细说一下吗，不太懂什么意思。
