### ISSUE TITLE
关于pc模拟安卓触摸操作优化问题

### ISSUE THREAD

**Issue by 382943436** [barry-ran/QtScrcpy#59]
这是我在手机上发现的差异真实触摸反馈和pc按键反馈不同，可能也会导致脚本执行在安卓不流畅的问题，是否需要root。有些手机是没有usb模拟点击的。
![8~`D}U5%~WK}@DV3 N7XBA](https://user-images.githubusercontent.com/32331488/70281996-678ee380-17f7-11ea-9ec8-d13305e54b8e.png)

**Comment by yxtj** [comment]
你这个图是怎么做出来的。我研究一下

**Comment by 382943436** [comment]
> 你这个图是怎么做出来的。我研究一下

开发者选项中的显示触摸对象和显示边缘布局或者类似选项
针对游戏映射来说pubg中鼠标模拟滑动镜头视角有卡顿的效果，这是我实际使用中遇到的问题

**Comment by yxtj** [comment]
> > 你这个图是怎么做出来的。我研究一下
> 
> 开发者选项中的显示触摸对象和显示边缘布局或者类似选项
> 针对游戏映射来说pubg中鼠标模拟滑动镜头视角有卡顿的效果，这是我实际使用中遇到的问题

位置差异的问题我复现不了。
我解决了卡顿问题，同时还修了一个鼠标移动的大bug。
你可以看一下我的pull request，或者去看一下我的仓库。

**Comment by barry-ran** [comment]
> > > 你这个图是怎么做出来的。我研究一下
> > 
> > 
> > 开发者选项中的显示触摸对象和显示边缘布局或者类似选项
> > 针对游戏映射来说pubg中鼠标模拟滑动镜头视角有卡顿的效果，这是我实际使用中遇到的问题
> 
> 位置差异的问题我复现不了。
> 我解决了卡顿问题，同时还修了一个鼠标移动的大bug。
> 你可以看一下我的pull request，或者去看一下我的fork。

感谢贡献，我也没有复现位置差异
