### ISSUE TITLE
希望跟进新版本的scrcpy比如1.10

### ISSUE THREAD

**Issue by yxtj** [barry-ran/QtScrcpy#60]
新版本的scrcpy添加了一些功能，比如限制最大帧率。
另外scrcpy 1.10还降低了画面传输延迟，对于游戏来说非常有用。

**Comment by mwhui** [comment]
弱弱的的问一句，在哪里可以看到scrcpy1.10版本啊

**Comment by yxtj** [comment]
https://github.com/Genymobile/scrcpy
现在已经更新到1.12.1了。

**Comment by barry-ran** [comment]
v1.1.0版本已经跟进1.12.1
