### ISSUE TITLE
无法截图

### ISSUE THREAD

**Issue by cnppla** [barry-ran/QtScrcpy#608]
“please select record save path”，但是菜单里找到录像保存路径设置区域，未能截图保存路径设置，大佬能说说在哪设置吗？

**Comment by Redeemer1001** [comment]
录像保存路径就是截图保存路径。这种问题试一试不就知道了……

**Comment by meteortears** [comment]
同上，无法截图

**Comment by cnppla** [comment]
> 录像保存路径就是截图保存路径。这种问题试一试不就知道了……



> 同上，无法截图。 设置录像路径后，也是无法截图，录像是可以的。

**Comment by BIGMONK** [comment]
一样的问题

**Comment by jetoHui520** [comment]
> 录像保存路径就是截图保存路径。这种问题试一试不就知道了……

nmd的试了不行啊

**Comment by OKSHIJIAN** [comment]
+1

**Comment by OKSHIJIAN** [comment]
任何设置，都需要重启生效。哈哈哈哈哈哈哈
