### ISSUE TITLE
How do I add more than one "SmallEyes" button? 如何添加多個“小眼睛”按鈕？

### ISSUE THREAD

**Issue by nutlost** [barry-ran/QtScrcpy#617]
I can create many common buttons except "SmallEyes". Anyone know how to make more than 1 button for "small eyes"? I don't know.

我可以創建一個通用按鈕。但除了“SmallEyes”的按鈕 如何為這個“小眼睛”創建多個按鈕？
![image](https://user-images.githubusercontent.com/106454766/171429152-358e1698-17ad-4e4f-b098-728e56a69df0.png)

**Comment by nutlost** [comment]
please help me @barry-ran

**Comment by barry-ran** [comment]
目前只支持一个SmallEyes

**Comment by barry-ran** [comment]
> > 目前只支持一个SmallEyes
> 
> is their any update??

QuickAssistant support mutil
