### ISSUE TITLE
窗口置顶选项不生效

### ISSUE THREAD

**Issue by HChenPan** [barry-ran/QtScrcpy#62]
大神啥时候看看这个bug能修复吗？
![image](https://user-images.githubusercontent.com/45525870/70417078-71d10c00-1a9b-11ea-86ba-a8ab12edd5cb.png)

**Comment by yxtj** [comment]
置顶的事手机画面的那个屏幕

**Comment by barry-ran** [comment]
点击置顶以后需要重新启动服务
