### ISSUE TITLE
submodule 问题

### ISSUE THREAD

**Issue by yanllllk** [barry-ran/QtScrcpy#623]
.gitmodules
定义的子模块URL最好改成https协议
现在这个ssh路径,无法正常克隆

**Comment by barry-ran** [comment]
为什么？

**Comment by yanllllk** [comment]
好吧,只是用了ssh还要绑证书,没有https匿名方便.

**Comment by barry-ran** [comment]
好的，后面改下

**Comment by barry-ran** [comment]
想了下不能改，否则在QtScrcpy中改完QtScrcpyCore的代码不方便提交
