### ISSUE TITLE
求助，这个怎么配合android studio用的，adb冲突啊

### ISSUE THREAD

**Issue by itzj90** [barry-ran/QtScrcpy#63]
求助

**Comment by barry-ran** [comment]
替换QtScrcpy目录中的adb为你已安装的adb即可

**Comment by fatasssnake** [comment]
adb.exe和另外两个dll文件替换过去还是不行
报错：
update devices...
adb run
AdbProcessImpl::error:* daemon not running; starting now at tcp:5037

AdbProcessImpl::error:could not read ok from ADB Server
* failed to start daemon

AdbProcessImpl::error:adb.exe: failed to check server version: cannot connect to daemon

Android Studio里面adb device有设备显示
