### ISSUE TITLE
error build in ubuntu 20.04

### ISSUE THREAD

**Issue by mji1010** [barry-ran/QtScrcpy#632]
i get this error.
Running /usr/local/bin/cmake /home/moha/barry-ran-QtScrcpy-5d62f85/QtScrcpy '-GCodeBlocks - Ninja' -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_CXX_COMPILER:STRING= -DCMAKE_C_COMPILER:STRING= -DCMAKE_PREFIX_PATH:STRING= -DQT_QMAKE_EXECUTABLE:STRING= in /tmp/QtCreator-FbVHVv/qtc-cmake-AiXkaasF.
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:18 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/tmp/QtCreator-FbVHVv/qtc-cmake-AiXkaasF/CMakeFiles/CMakeOutput.log".
See also "/tmp/QtCreator-FbVHVv/qtc-cmake-AiXkaasF/CMakeFiles/CMakeError.log".
CMake process exited with exit code 1.

**Comment by barry-ran** [comment]
There is something wrong with your environment. [CI is normal](https://github.com/barry-ran/QtScrcpy/actions/workflows/ubuntu.yml)
