### ISSUE TITLE
中文输入APP不响影键盘输入该如何解决呢？

### ISSUE THREAD

**Issue by wuyusite** [barry-ran/QtScrcpy#64]
是个好东西，可是不能输入中文这一点很痛苦呀

**Comment by wuyusite** [comment]
一个多星期，我测试几款国内热门的中文输入法，和在国内不用能有的GO输入法。
GO输入法可以响影键盘输入中文，而且有五笔输入功能，但在国内没有上架和Google play对地区的限制是硬伤，再加上使用设计上真心不是给国人用的，我用了两天就放弃了。
讯飞输入法也可以正常响影键盘输入中文，但硬伤是不支持五笔，对于我这个PC输法不会用拼音的人来说，这是硬伤。如果你不需要五笔输入，迅飞是个不错的选择。
QQ输入法，这个是我最推荐的，输入方式齐全，也支持五笔输入还能五笔拼音混输很不错，而且我发现它是唯一一款有针对硬件手机输入做优化支持的输入法，在我用键盘录入内容时它会自动把手机上的软键盘去掉，这个功能很赞。
其它的输入法很不稳定，有的手机可以用，有的手机不行，搜狗输入法基本上就是全系列都不能。

写在最后：个人最推荐QQ输入法，虽然我很不喜欢用QQ家族的东西，但这一次让我对QQ家族有了改观^_^

**Comment by barry-ran** [comment]
我用搜狗输入法可以输入中文呢，你测试了QQ输入法最稳定吗？

**Comment by khalitt** [comment]
> 我用搜狗输入法可以输入中文呢，你测试了QQ输入法最稳定吗？

请问是电脑上装搜狗还是手机上装呢? 我电脑上装了, 手机上自带MIUI的搜狗输入法, 不行

**Comment by barry-ran** [comment]
> > 我用搜狗输入法可以输入中文呢，你测试了QQ输入法最稳定吗？
> 
> 请问是电脑上装搜狗还是手机上装呢? 我电脑上装了, 手机上自带MIUI的搜狗输入法, 不行

手机上装一个普通的搜狗输入法
