### ISSUE TITLE
V2.1.0 AND V2.1.1==>  X64 AdbProcessImpl::error:stack corruption detected (-fstack-protector)

### ISSUE THREAD

**Issue by Broukmiken** [barry-ran/QtScrcpy#698]
force close
w11 64 bits, Android phone arm 64 v8, android 11

AdbProcessImpl::error:stack corruption detected (-fstack-protector)
with previous version (2.0.1)  no force close at all.

And where is the record button please ?
i only can see the screenshot button
i don't know how to record the screen in mkv or mp4 even if i have set the record directory.
thanks.

**Comment by barry-ran** [comment]
2.1.2 fixed

**Comment by Broukmiken** [comment]
@barry-ran 

thanks to have reopened this #698 because 2.1.1hasen't fixed the issue.

**Comment by PockerKID** [comment]
Win11 x64 , Samsung Note10+ (Android 12) 
same issues

``` text
update devices...
"本软件完全开源免费，作者不对使用该软件产生的一切后果负责。你可以在以下地址下载："

"QtScrcpy 2.1.1 <https://github.com/barry-ran/QtScrcpy>"

AdbProcessImpl::error:* daemon not running; starting now at tcp:5037

AdbProcessImpl::error:* daemon started successfully

AdbProcessImpl::out:List of devices attached
RFCM90235JD	device

start server...
AdbProcessImpl::out:D:/Tools/QtScrcpy-win-x64-v2.1.1/scrcpy-server: 1 file pushed, 0 skipped. 53.5 MB/s (41159 bytes in 0.001s)

AdbProcessImpl::out:[server] INFO: Device: samsung SM-N9760 (Android 12)

server start finish in 0.447s

AdbProcessImpl::out:[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'

AdbProcessImpl::error:stack corruption detected (-fstack-protector)

update devices...
adb run
```

**Comment by iuriimattos2** [comment]
same issue in samsung M51

**Comment by Chengxcy** [comment]
同样的版本，Win11 x64 , Samsung Note10+ (Android 12)
同样的问题， 2.0.1 工作正常。打开2.11版本一闪而过。

**Comment by barry-ran** [comment]
[v2.1.2](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.1.2)

**Comment by tvanhuu** [comment]
> [v2.1.2](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.1.2)

not work with win11 + xiaomi note 11 Pro. Please check it. Thank you
