### ISSUE TITLE
Mac安装后辅助功能无法勾选也无法删除

### ISSUE THREAD

**Issue by lxxself** [barry-ran/QtScrcpy#7]
![image](https://user-images.githubusercontent.com/8406766/60584226-4137c880-9dbf-11e9-9205-9ded73055464.png)

**Comment by chenyy0708** [comment]
我也是这个问题，老哥找到原因了吗？还是要作者修复才能行

**Comment by chenyy0708** [comment]
我也是这个问题，老哥找到原因了吗？还是要作者修复才能行@barry-ran

**Comment by barry-ran** [comment]
代码上已经修复这个问题，目前还没有打包，下个版本会带上

**Comment by sunzongzheng** [comment]
我这边mac下点击屏幕是无效的，是同一个问题吗？现在投屏功能正常，但是电脑无法去触控操作

**Comment by barry-ran** [comment]
> 我这边mac下点击屏幕是无效的，是同一个问题吗？现在投屏功能正常，但是电脑无法去触控操作

什么手机，小米的话看下FAQ里有说明需要打开一个设置

**Comment by sunzongzheng** [comment]
@barry-ran 还真是小米，设置以后可以了，流畅的一批，甩市面上那些几条街，牛逼！


再反馈一个小问题：全屏以后，退出全屏，投屏区右边的操作按钮就不见了，没有找到重新开启的菜单

**Comment by barry-ran** [comment]
> @barry-ran 还真是小米，设置以后可以了，流畅的一批，甩市面上那些几条街，牛逼！
> 
> 再反馈一个小问题：全屏以后，退出全屏，投屏区右边的操作按钮就不见了，没有找到重新开启的菜单

可以截图看看吗？没有复现这个问题，另外，重新开启的菜单指的是什么？

**Comment by sunzongzheng** [comment]
![image](https://user-images.githubusercontent.com/12635613/67927601-fa829f80-fbf3-11e9-9c97-718b76e9721b.png)

我这边的复现步骤就是：点击全屏按钮，然后显示系统的所有窗口，把刚刚全屏的窗口拖下来，这样就做到了退出全屏，然后上面的菜单就消失了

**Comment by barry-ran** [comment]
> ![image](https://user-images.githubusercontent.com/12635613/67927601-fa829f80-fbf3-11e9-9c97-718b76e9721b.png)
> 
> 我这边的复现步骤就是：点击全屏按钮，然后显示系统的所有窗口（mac四指上划），把刚刚全屏的窗口拖下来，这样就做到了退出全屏，然后上面的菜单就消失了

这个场景确实没有考虑到，双击或ESC退出全屏是没问题的吧

**Comment by sunzongzheng** [comment]
esc退出全屏正常，双击菜单栏我这边尝试是无效的，mac下应该不能双击退出全屏吧，我还没有用过这种方式

**Comment by barry-ran** [comment]
> esc退出全屏正常，双击菜单栏我这边尝试是无效的，mac下应该不能双击退出全屏吧，我还没有用过这种方式

记错了，看了下代码，只有ESC退出全屏方式

**Comment by AceInAndroid** [comment]
我也是~几号发包啊老哥

**Comment by barry-ran** [comment]
v1.2.0已修复
