### ISSUE TITLE
mac中启动配置无法保存

### ISSUE THREAD

**Issue by flowercoder** [barry-ran/QtScrcpy#703]
使用版本 v2.1.1
apple m1机器
系统12.4
能给的权限应该都给了，目前启动配置没法保存，每次进行都要手动设置，否则就会很糊。
希望能下个版本能解决。
如果无法解决，希望能放到配置文件中。
另外看到config.ini文件中可以手动指定编码器
希望能看到相关的例子或是布道。

**Comment by conghuahuadan** [comment]
同M1机器，每次都需要手动设置

**Comment by barry-ran** [comment]
2.1.2
