### ISSUE TITLE
M1 12.6 安装2.1.1后无法使用

### ISSUE THREAD

**Issue by lxxself** [barry-ran/QtScrcpy#710]
今天看有新版顺手更新了下，之前使用时正常的。
在 2.1.1下日志框内报错如下，所有按钮点了都报错

> update devices...
adb run
AdbProcessImpl::error:rosetta error: /var/db/oah/6e35bb8c79a9ce28678c02aaf0e72aec2d34e7c61d702c9d9ebed473f3ceee80/d01554781e053c6ec82799fecb7f9c109a6542a085611b9666f683279d3fae92/adb.aot: attachment of code signature supplement failed: 1
qprocess start error:/Applications/QtScrcpy.app/Contents/MacOS/adb devices

请问这个是啥问题

**Comment by laocu333** [comment]
https://support.apple.com/zh-cn/HT202491
参考这个，我是m1 13.1  正常用
