### ISSUE TITLE
安卓12设备无法正常显示

### ISSUE THREAD

**Issue by Etherrrr** [barry-ran/QtScrcpy#718]
从2.0.0开始的版本连接安卓12设备后无法显示投屏窗口

log中显示内容如下
`start server...
AdbProcessImpl::out:E:/QtScrcpy-win-x64-v2.1.1/scrcpy-server: 1 file pushed, 0 skipped. 28.7 MB/s (41159 bytes in 0.001s)`

**Comment by hai1277** [comment]
请问这个有解决方法吗？
