### ISSUE TITLE
能否实现手机显示熄屏，电脑端保持控制

### ISSUE THREAD

**Issue by imkyleshing** [barry-ran/QtScrcpy#719]
貌似没看到这个功能，虽然我也知道投屏是把手机显示的原原本本展示出来

**Comment by shiqianwei0508** [comment]
有个眼睛样式的按钮“关闭屏幕”

**Comment by imkyleshing** [comment]
> 

万分感谢！！！ 属于是灯下黑了

**Comment by mbj2014** [comment]
设计有2个类似眼睛的按钮，带斜线的那个是关闭屏幕。

不过这个是不是应该合并成一个按钮，或者高亮当前状态，可以从电脑屏幕上就知道当前手机屏幕是否亮着？
