### ISSUE TITLE
Arch Linux 打包和运行 1.1.0 版本的问题

### ISSUE THREAD

**Issue by BruceZhang1993** [barry-ran/QtScrcpy#73]
系统信息
OS: Arch Linux
OS Version: Latest stable
Qt Version: 5.14.0
Kernel Version: 5.4.13-zen1-1-zen
CPU: 8 × AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx

AUR: https://aur.archlinux.org/packages/qt-scrcpy/
打包脚本：https://aur.archlinux.org/cgit/aur.git/tree/?h=qt-scrcpy

运行终端报错

	""
	"QtScrcpy"
	fish: 'QtScrcpy' terminated by signal SIGSEGV (Address boundary error)

Coredump 信息

	           UID: 1000 (bruce)
	           GID: 1000 (bruce)
	        Signal: 11 (SEGV)
	     Timestamp: Tue 2020-01-21 10:49:50 CST (17s ago)
	  Command Line: ./QtScrcpy
	    Executable: /home/bruce/Projects/AUR/qt-scrcpy/src/QtScrcpy-1.1.0/output/linux/release/QtScrcpy
	 Control Group: /user.slice/user-1000.slice/session-3.scope
	          Unit: session-3.scope
	         Slice: user-1000.slice
	       Session: 3
	     Owner UID: 1000 (bruce)
	       Boot ID: cc0568699c0a4200a2a1ee8c57b69751
	    Machine ID: 64709a9359c34080969d2e4d6ebf1ea5
	      Hostname: bruce-laptop
	       Storage: /var/lib/systemd/coredump/core.QtScrcpy.1000.cc0568699c0a4200a2a1ee8c57b69751.108258.1579574990000000000000.lz4
	       Message: Process 108258 (QtScrcpy) of user 1000 dumped core.
	                
	                Stack trace of thread 108258:
	                #0  0x00007f705871dbd3 _ZN7QString6appendERKS_ (libQt5Core.so.5 + 0x14bbd3)
	                #1  0x00005613240e3194 n/a (/home/bruce/Projects/AUR/qt-scrcpy/src/QtScrcpy-1.1.0/output/linux/release/QtScrcpy + 0x3d194)
	                #2  0x0000000000000000 n/a (n/a + 0x0)

GDB 调试信息

	(gdb) r
	Starting program: /home/bruce/Projects/AUR/qt-scrcpy/src/QtScrcpy-1.1.0/output/linux/release/QtScrcpy 
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/usr/lib/libthread_db.so.1".
	/usr/lib/../share/gcc-9.2.0/python/libstdcxx/v6/xmethods.py:731: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
	  refcounts = ['_M_refcount']['_M_pi']
	[New Thread 0x7ffff2227700 (LWP 106066)]
	[New Thread 0x7fffeb80d700 (LWP 106067)]
	""
	"QtScrcpy"
	
	Thread 1 "QtScrcpy" received signal SIGSEGV, Segmentation fault.
	0x00007ffff6c8fbd3 in QString::append(QString const&) () from /usr/lib/libQt5Core.so.5

**Comment by barry-ran** [comment]
现在还没研究过linux打包，也是QtScrcpy没有提供Linux包的原因

**Comment by huyizheng** [comment]
刚发现，1.2.1版运行已经不吐核了，能正常连接手机，录屏我没试
但是退出程序的时候会吐核：
```
                Stack trace of thread 56805:
                #0  0x00007f986c800b08 _ZNK7QObject6threadEv (libQt5Core.so.5 + 0x2cfb08)
                #1  0x00007f986c7e0c43 _ZN11QMetaObject16invokeMethodImplEP7QObjectPN9QtPrivate15QSlotObjectBaseEN2Qt14ConnectionTypeEPv (libQt5Core.so.5 + 0x2afc43)
                #2  0x000055ca71fc503e n/a (QtScrcpy + 0x3c03e)
                #3  0x00007f986c5f2ad8 n/a (libQt5Core.so.5 + 0xc1ad8)
                #4  0x00007f986c5f2bea n/a (libQt5Core.so.5 + 0xc1bea)
                #5  0x00007f986c5bf1d4 _ZNK14QMessageLogger7warningEPKcz (libQt5Core.so.5 + 0x8e1d4)
                #6  0x00007f986c5cc94e n/a (libQt5Core.so.5 + 0x9b94e)
                #7  0x00007f98674d14fa n/a (libfcitxplatforminputcontextplugin.so + 0x144fa)
                #8  0x00007f98674d1807 n/a (libfcitxplatforminputcontextplugin.so + 0x14807)
                #9  0x00007f98674d3f26 n/a (libfcitxplatforminputcontextplugin.so + 0x16f26)
                #10 0x00007f98674d4199 n/a (libfcitxplatforminputcontextplugin.so + 0x17199)
                #11 0x00007f9868959124 _ZN15QXcbIntegrationD1Ev (libQt5XcbQpa.so.5 + 0x3f124)
                #12 0x00007f98689591aa _ZN15QXcbIntegrationD0Ev (libQt5XcbQpa.so.5 + 0x3f1aa)
                #13 0x00007f986cd4b3cc _ZN22QGuiApplicationPrivateD1Ev (libQt5Gui.so.5 + 0x1263cc)
                #14 0x00007f986d427d2a _ZN19QApplicationPrivateD0Ev (libQt5Widgets.so.5 + 0x159d2a)
                #15 0x00007f986c80a6f2 _ZN7QObjectD2Ev (libQt5Core.so.5 + 0x2d96f2)
                #16 0x00007f986c7d8bf0 _ZN16QCoreApplicationD2Ev (libQt5Core.so.5 + 0x2a7bf0)
                #17 0x00007f986d429d59 _ZN12QApplicationD2Ev (libQt5Widgets.so.5 + 0x15bd59)
                #18 0x000055ca71fc39c2 n/a (QtScrcpy + 0x3a9c2)
                #19 0x00007f986c025023 __libc_start_main (libc.so.6 + 0x27023)
                #20 0x000055ca71fc3c8e n/a (QtScrcpy + 0x3ac8e)
                
                Stack trace of thread 56807:
                #0  0x00007f986c0f2abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f986b2cd7a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
                #2  0x00007f986b2cd871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
                #3  0x00007f986c82f0d0 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe0d0)
                #4  0x00007f986c7d557c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a457c)
                #5  0x00007f986c5f9e62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e62)
                #6  0x00007f9868894b28 n/a (libQt5DBus.so.5 + 0x15b28)
                #7  0x00007f986c5fafd6 n/a (libQt5Core.so.5 + 0xc9fd6)
                #8  0x00007f986c51846f start_thread (libpthread.so.0 + 0x946f)
                #9  0x00007f986c0fd3d3 __clone (libc.so.6 + 0xff3d3)
```
