### ISSUE TITLE
关于Redmi k20pro win10 64鼠标键盘操作均无效的问题

### ISSUE THREAD

**Issue by loveempathy** [barry-ran/QtScrcpy#76]
下载项目解压链接直接运行后显示没有问题，但是键鼠无法操作手机，不晓得是不是我操作不对还是哪里的问题，手机：Redmi K20 Pro   MIUI：11.0.5稳定版   Android 10    电脑操作系统：windows 10 x64

**Comment by barry-ran** [comment]
是因为没有开相关权限
https://github.com/barry-ran/QtScrcpy/blob/master/docs/FAQ.md
