### ISSUE TITLE
文档中没有写明如何在启动 scrcpy 时添加参数，希望补正

### ISSUE THREAD

**Issue by joebnb** [barry-ran/QtScrcpy#763]
如题，文档中没有，而在实际使用时有时候官方为了解决某个功能点新添加的功能，需要通过命令行参数开启，但在中文文档和英文文档中似乎都没有看到，如何在启动时添加参数，（同时希望在高级模式下可以在启动时预览下启动的命令是否符合预期）

**Comment by joebnb** [comment]
比如 https://github.com/Genymobile/scrcpy#text-injection-preference

**Comment by barry-ran** [comment]
QtScrcpy没开放这个选项

**Comment by gbcbooks** [comment]
有计划开放吗？ 目前看，scrcpy无法输入中文的问题，官方比较推荐用scrcpy --hid-keyboard，模拟物理键盘来解决呢
