### ISSUE TITLE
希望跟进scrcpy 1.12.1版本 

### ISSUE THREAD

**Issue by yxtj** [barry-ran/QtScrcpy#77]
scrcpy自1.10版本之后的增加了官方多点触控的支持，修复了大量bug，另外还升级了FFmpeg提高了效率。
希望跟进。

**Comment by barry-ran** [comment]
感谢提醒，TODO.md里有记录最后同步scrcpy的commit，目前已经是同步到1.12.1版本了，稍后升级ffmpeg
