### ISSUE TITLE
使用Scrcpy正常链接。但是QtScrcpy启动一直没反应这样显示的

### ISSUE THREAD

**Issue by heiniao998** [barry-ran/QtScrcpy#783]
一直重复这样显示
update devices...
adb run
AdbProcessImpl::out:List of devices attached
99NAY1AeJ7	device

update devices...
adb run
AdbProcessImpl::out:List of devices attached
99NAY1AeJ7	device

update devices...
adb run
AdbProcessImpl::out:List of devices attached
99NAY1AeJ7	device
这样怎么解决 感谢大佬们回答一下
设备链接正常。无法启动服务

**Comment by Swordelf** [comment]
我的也这样
