### ISSUE TITLE
截图可以调用安卓系统的截图，直接保存到图库也方便

### ISSUE THREAD

**Issue by chise0713** [barry-ran/QtScrcpy#789]

**Comment by sonnabanana** [comment]
（个人理解不一定对）应用程序有时会设置 secure flag 阻止系统截屏。虽然在最新版本的 Android 系统这样也会导致 Scrcpy/QtScrcpy 输出黑屏，但在以前的系统版本里只会阻止截屏动作，并不妨碍视频输出。
