### ISSUE TITLE
启用从蓝牙连接的远程设备播放音频-Enable audio playback from a Bluetooth-connected remote device

### ISSUE THREAD

**Issue by ghost** [barry-ran/QtScrcpy#793]
https://learn.microsoft.com/zh-CN/windows/uwp/audio-video-camera/enable-remote-audio-playback
请问能实现吗，感觉挺高级。
Can it be achieved, it feels quite advanced.

**Comment by StarryskyLL** [comment]
Microsoft Store有Bluetooth Audio Receiver这个软件用的就是这个

**Comment by StarryskyLL** [comment]
> 

应该是蓝牙兼容的原因,我用着还好,但是音质不行,我也很少用
