### ISSUE TITLE
LineagesOS剪贴板互通功能失效

### ISSUE THREAD

**Issue by dream2333** [barry-ran/QtScrcpy#823]
在小米8、小米8se、pixel1的lineage上均发现了剪贴板互通失效

**Comment by viarotel** [comment]
有同样的问题

**Comment by viarotel** [comment]
最后没办法自己写了一个，能同步了，可以试试 [escrcpy](https://github.com/viarotel-org/escrcpy) 与 scrcpy 最新版本保持同步
