### ISSUE TITLE
QtScrcpy鼠标点击没反应，只能看到画面，无法点击手机屏幕

### ISSUE THREAD

**Issue by 1265578519** [barry-ran/QtScrcpy#897]
开发者选项给了USB调试，USB模拟鼠标，USB安全操作最高权限

小米miui14 安卓12

**Comment by lonznt** [comment]
两年没更了，不知道是不是开发者放弃了？

**Comment by qwer2y** [comment]
同样的问题

**Comment by 1265578519** [comment]
我找到雷电模拟器自带的“无界趣连”可以正常用，电脑控制手机玩游戏过模拟器检测

**Comment by XhnPLayer** [comment]
安卓14 不能 鼠标点击用不了了。

**Comment by 1265578519** [comment]
我安卓12可以用雷电的那个玩QQ飞车

**Comment by VacantHusky** [comment]
两年没更新了，已经不支持安卓14了。安卓14想玩fps游戏的，可以看看我复刻的项目，https://github.com/VacantHusky/scrcpyFpsGameKeyMap

**Comment by kunji-vs** [comment]
我的也是，昨天更新系统之后就只能显示画面了。无法控制。不过用原版的scrcpy可以控制。就是有许多命令没有封装，需要自己手动在控制台配置

**Comment by sd950216** [comment]
> It hasn't been updated for two years, and Android 14 is no longer supported. Android 14 If you want to play fps games, you can take a look at my reproduction project, https://github.com/VacantHusky/scrcpyFpsGameKeyMap

dude, pls fix left joystick is not stable when moving left and right afterwards or vice versa, otherwise everything is great.

**Comment by cool-delete** [comment]
作者闭源了一个新项目了 叫极限投屏 我14系统没换之前一样的问题 换了闭源的这个就好了 不知道原理 可能是adb没更新?

**Comment by VacantHusky** [comment]
> > It hasn't been updated for two years, and Android 14 is no longer supported. Android 14 If you want to play fps games, you can take a look at my reproduction project, https://github.com/VacantHusky/scrcpyFpsGameKeyMap
> 
> dude, pls fix left joystick is not stable when moving left and right afterwards or vice versa, otherwise everything is great.

@sd950216 You may want to check if the coordinates are set correctly. However, it is indeed prone to errors when pressing keys frequently.

**Comment by sd950216** [comment]
@VacantHusky i tried many times even with different settings in the game , everything is good except for what i mentioned, the issue only occurs when you press left then right immediately left (while holding aka strafe in fps games ) makes the left joystick completely frozen until i press it again (after release) , pls check it out in codm if possible + thank you so much for ur effort ❤✅

**Comment by ganyanchuan1989** [comment]
QtScrcpy-win-x64-v2.2.1.zip 红米note 11 pro 依旧不行，已经开启USB 调试 和 USB 调试（安全设置）

**Comment by 1426781227** [comment]
启用视图属性检查功能
