### ISSUE TITLE
How do i add custom keymapping?

### ISSUE THREAD

**Issue by fluffyloopy** [barry-ran/QtScrcpy#90]

**Comment by fluffyloopy** [comment]
the keymaps dont work on pubgm
wasd and v button only works

**Comment by barry-ran** [comment]
[Chinese documents only](https://github.com/barry-ran/QtScrcpy/blob/master/docs/%E6%8C%89%E9%94%AE%E6%98%A0%E5%B0%84%E8%AF%B4%E6%98%8E.md)

**Comment by m4heshd** [comment]
Such a waste having just chinese documentation. More people would've been able to contribute if it was in English too.

**Comment by barry-ran** [comment]
thank you for your reminder, I will provide English documentation soon
