### ISSUE TITLE
v2.2.0缺少dmg包, 或者需要自行编译吗?

### ISSUE THREAD

**Issue by GitHubWebb** [barry-ran/QtScrcpy#918]
v2.2.0 [Latest](https://github.com/barry-ran/QtScrcpy/releases/latest)

 91a6b4c
![Xnip2024-03-04_17-24-22](https://github.com/barry-ran/QtScrcpy/assets/24510234/358d40e7-8bf7-4e64-b2d4-206087121a90)

**Comment by 87074139** [comment]
如何自行编译我没有java环境

**Comment by huhengbo** [comment]
同求个2.2.0的dmg包

**Comment by gumeier** [comment]
我编译好了MacOS 版本的了，怎么分享给你们？

**Comment by Dinu5288-KG** [comment]
i also need for mac os

**Comment by GitHubWebb** [comment]
> 我编译好了MacOS 版本的了，怎么分享给你们？

上传下附件

**Comment by IsGuibo** [comment]
> 我编译好了MacOS 版本的了，怎么分享给你们？

好兄弟，可以发一份到我邮箱吗？838912974@qq.com

**Comment by barry-ran** [comment]
[v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1) fixed
