### ISSUE TITLE
无法录屏

### ISSUE THREAD

**Issue by GhostDog-lam** [barry-ran/QtScrcpy#920]
Could not send packet to recorder

**Comment by rhwong** [comment]
Same problem

log:
```
Could not send packet to recorder
Could not send packet to recorder
Could not send packet to recorder
```

Version:QtScrcpy-win-x64-v2.2.0

**Comment by barry-ran** [comment]
[v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1) fixed
