### ISSUE TITLE
qtscrcpy not working 

### ISSUE THREAD

**Issue by RohitKushvaha01** [barry-ran/QtScrcpy#955]
i downloaded the ubuntu version and tried to run in fedora 39 after fixing dependency the the gui showd up and recognized the android 11 device via usb but after that screen of android devices dosent appear even after sstarting server installing it etc

**Comment by fox0001** [comment]
Running with QtScrcpy-ubuntu-22.04-gcc_64.zip on Lubuntu 22.04.4, I got errors as follow:

```
start server...
AdbProcessImpl::out:/opt/deploy/QtScrcpy/scrcpy-server: 1 file pushed, 0 skipped. 22.9 MB/s (69007 bytes in 0.003s)

AdbProcessImpl::error:[server] ERROR: The server version (2.4) does not match the client (2.1.1)
java.lang.IllegalArgumentException: The server version (2.4) does not match the client (2.1.1)

AdbProcessImpl::error:at com.genymobile.scrcpy.Options.parse(Options.java:237)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:231)
	at com.genymobile.scrcpy.Server.main(Server.java:214)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:366)
```

**Comment by wch1618** [comment]
Replace 'scrcpy-server' with [scrcpy v2.1.1](https://github.com/Genymobile/scrcpy/releases/tag/v2.1.1)

**Comment by ChienliWang** [comment]
If you install it through scoop
You can manually delete and replace the 'config/config.ini' file in the corresponding installation directory
His original file is in folder 'config.original'
![image](https://github.com/barry-ran/QtScrcpy/assets/37263785/940303d3-86e4-4203-a8f3-c4148b7be062)
