### ISSUE TITLE
开启投屏成功，关闭设备屏幕后，点击返回主页，桌面图标全部不显示了

### ISSUE THREAD

**Issue by imzhengziyi** [barry-ran/QtScrcpy#97]
版本：QtScrcpy-win-x64-v1.2.1
手机：小米9
系统：MIUI 11.0.5稳定版

投屏成功，关闭设备屏幕后，点击返回主页，桌面图标全部不显示了！

另外咨询一下，自己写的json脚本，因为屏幕是2340*1080的，计算坐标的时候也是按照此分辨率来计算的，但是映射后只有1-2个键是正常的，很多键位是错的或者没有反应的是怎么回事呢！

**Comment by barry-ran** [comment]
仔细阅读[此说明](https://github.com/barry-ran/QtScrcpy/blob/master/docs/%E6%8C%89%E9%94%AE%E6%98%A0%E5%B0%84%E8%AF%B4%E6%98%8E.md)

**Comment by imzhengziyi** [comment]
感谢回复，按键映射已经完成！
