### ISSUE TITLE
无线的IP是否有可能支持域名解析？

### ISSUE THREAD

**Issue by lxxself** [barry-ran/QtScrcpy#98]
因可以局域网无限连接，进而联想到远程连接。测试过可以使用IPV6 IP地址远程连接，远程端口映射后IPV4 IP也可连接。但似乎不支持域名。

另，是否有计划移植开发到Android端，实现手机控制手机。

**Comment by barry-ran** [comment]
ipv4公网的话确实可以无线连接，已经有朋友基于此原理开发了类似远程租赁的平台，域名的话需要额外解析一下，也是可以做到的，移植到Android端近期没有此计划

**Comment by EasyKevin** [comment]
手机控制手机应该需要Root吧,貌似需要执行到adbd的相关操作

**Comment by lxxself** [comment]
> 手机控制手机应该需要Root吧,貌似需要执行到adbd的相关操作

 类似airDroid，应该先行打开adb端口就行吧

**Comment by lxxself** [comment]
> ipv4公网的话确实可以无线连接，已经有朋友基于此原理开发了类似远程租赁的平台，域名的话需要额外解析一下，也是可以做到的，移植到Android端近期没有此计划

感谢回复
