### ISSUE TITLE
问题：一到输密码的环节，就会黑屏！

### ISSUE THREAD

**Issue by AShanWang** [barry-ran/QtScrcpy#981]
问题：一到输密码的环节，就会黑屏！
手机端正常显示！
返回到非密码页面就又正常显示了。

请问如何在输密码的页面上也能正常显示呢？
我用的是windwos11系统，安卓14(小米11pro)。

**Comment by lb091188** [comment]
安卓手机的隐私保护机制，估计是无法解决

**Comment by AShanWang** [comment]
> 安卓手机的隐私保护机制，估计是无法解决

关闭手机的安全键盘，或许可以解决

**Comment by joket1999** [comment]
我也是遇到这问题，比如看网络课程，只有手机版app，我想投屏到电脑上看，播放器禁止录屏和截屏，一投屏就黑屏。
