### ISSUE TITLE
手机升级到Android 14后，投屏时点击“关闭屏幕”闪退

### ISSUE THREAD

**Issue by alche1224** [barry-ran/QtScrcpy#987]

**Comment by Lee0535** [comment]
我也出现同样的问题，点击「关闭屏幕」或者『打开屏幕』都会投屏关闭。
AdbProcessImpl::error:Native registration unable to find class 'com/android/server/TrustedUIService'; aborting...

**Comment by hupan666** [comment]
同样的错误，至今尚未修复

**Comment by sadomasoc** [comment]
同样的问题，无论是USB还是WIFI连接，都会出现

**Comment by alche1224** [comment]
今天下载了3.0.1版本，问题已解决
